.github/workflows/deploy-cluster.yml, Makefile, cluster/config/test.sh, cluster/terraform/config/test.tfvars.json, cluster/terraform/variables.tf
Test environment created for AKS cluster
- Added terraform code for the test environment
- Added certificate to the cluster.
- Added  DNS zone*.test-teacherservices-cloud-2 to Production environment manually
- Add workflow to deploy to Azure test environment.
Successful Deployment: [here](https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/3949396385/jobs/6760556305)
[Here](https://portal.azure.com/?Microsoft_Azure_PIMCommon=true&feature.msaljs=false#@platform.education.gov.uk/resource/subscriptions/20da9d12-7ee1-42bb-b969-3fe9112964a7/resourceGroups/s189t01-tsc-ts-rg/overview)
=> Add test AKS cluster

Makefile, README.md
Make it easier to configure cluster credentials locally for kubectl
=> Get cluster credentials

cluster/terraform/config/production.tfvars.json, cluster/terraform/config/test.tfvars.json
**Context**
Add bat namespaces to test and production clusters.
Remove current namespaces.
(development will be removed later from test as it is currently in use)
Update cluster json files
deploy-plan
=> Create bat namespaces in test and prod clusters

cluster/terraform/main.tf, cluster/terraform/variables.tf
Added the following resource deployments:
- A redis cache subnet in existing VNet
- Private DNS Zone - `privatelink.redis.cache.windows.net`
-  [Documentation behind the private DNS zone name reasoning](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-private-link#how-do-i-connect-to-my-cache-with-private-endpoint)
- Added resource blocks to create the redis-subnet and private DNS zone
- Separated the DNS zone names from the subnet object as `privatelink.redis.cache.windows.net` will not be a suffix-style private DNS zone
- Added a condition and lookups on dynamic delegation resource deployment as `redis-subnet` will not have a service delegation
- Minor: reworded `delegations` to `delegation` as I believe only one service can be delegated to a subnet
This PR has been …
=> Add redis subnet and Private DNS zone

cluster/terraform/config/production.tfvars.json, cluster/terraform/config/test.tfvars.json
The test cluster is already under pressure with 6 nodes
Bumping production as well
Check test cluster node pool is already at capacity
=> Increase node pools max nodes

cluster/terraform/.terraform.lock.hcl, cluster/terraform/terraform.tf, custom_domains/terraform/infrastructure/.terraform.lock.hcl, custom_domains/terraform/infrastructure/terraform.tf
Keep up-to-date and potentially fix intermittent issues we had with azurerm and subnet delegation
- Run terraform plan with AKS
- Run terraform plan with DNS
- Check cluster3
=> [204] Update terraform providers

scripts/konduit.sh
Now fix OTHERARGS for the psql command in konduit
=> Fix OTHERARGS for psql

.github/actions/deploy-environment/action.yml, README.md
Fix for: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/4347274123
Ran successfully here: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/4347370521
=> [218] Fix cluster terraform path

cluster/terraform_kubernetes/ingress_controller.tf
The client IP was not available to the Apply app
- Change ingress load balancer network traffic to Local to preserve the source IP
- Configure x-forwarded-for headers in ingress-nginx
- Login with support to qa2. You should receive an email with your real IP.
- The [http-https-echo](https://hub.docker.com/r/mendhak/http-https-echo) test app has been deployed to the test environment. You can verify all headers via
- https://http-https-echo.test.teacherservices.cloud/
- https://pen.apply-for-teacher-training.education.gov.uk/ (manually edited route)
=> [219] Keep the client IP in requests to applications

scripts/konduit.sh
Enable redis-cli connection to Azure redis backing service.
Allows connection to cache or queue (with -r) instances.
For an app using azure redis
konduit.sh app-service -- redis-cli (connect to REDIS_URL)
konduit.sh -r REDIS_CACHE_URL app-service -- redis-cli (connect to REDIS_CACHE_URL)
For an app using container redis 
konduit.sh -a app-service -- redis-cli
=> Enable azure backing service for konduit redis-cli

scripts/konduit.sh
Add the ability to set the timeout to a specified value.
Add a new option `-t` to override the default timeouts.
Restored production backup to production AKS database with new parameter
`bin/konduit.sh -i apply_prod_2023-03-27.sql.gz -c -t 7200 apply-production -- psql`
=> Add timeout override

Makefile
The pipeline blocked because the make commands require confirmation. Add an override when it runs in ci.
- Run: `make test`. It should block you
- Run: `make ci test`. It should pass
=> [294] Auto confirm make commands in pipeline

.gitignore, Makefile, README.md, cluster/terraform_aks_cluster/.terraform.lock.hcl, cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_aks_cluster/main.tf, cluster/terraform_aks_cluster/network.tf, cluster/terraform_aks_cluster/variables.tf, cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/dns.tf, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/namespaces.tf, cluster/terraform_kubernetes/statuscake.tf, cluster/terraform_kubernetes/terraform.tf, cluster/terraform_kubernetes/tls.tf, cluster/terraform_kubernetes/variables.tf, documentation/rebuild-cluster.md, scripts/export_aks_resources.sh, scripts/import_aks_resources.sh
It may be required to rebuild the cluster. We want to be able to do it without impacting users. This adds commands and documentation to enable it.
- Create a dev cluster
- Deploy Apply review app to it (dv_review_aks)
- Test Apply continuously to check for downtime
- Follow the new documentation to rebuild the cluster
=> [300] Zero downtime cluster rebuild

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Add tra-dev and tra-test namespaces to the test cluster, and tra-production to the prod cluster
=> Add tra k8s namespaces

Makefile
The pipeline was hanging as it was missing auto approve
=> [261] Fix DNS pipeline auto approve

cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/welcome_app.tf, documentation/aks-upgrade.md
Deploy welcome apps to all clusters so we can use them during cluster upgrades
Deployed to platform-test: https://www.platform-test.teacherservices.cloud/
=> [301] Test upgrade clusters with welcome apps

.github/actions/deploy-environment/action.yml
Basic smoke test to validate each cluster deployment and allow the pipeline to progress to next stage
- Success: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/4885354951
- Test failure: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/4885367943
- Test failure: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/4885393820
=> [94] Run basic smoke tests after cluster deployment

documentation/monitoring.md
Add documentation for cluster monitoring
check monitoring.md
=> Add monitoring doc

.github/workflows/deploy-cluster.yml
Mask terraform ARM variables as they may be exposed in the pipeline
Check variables in https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/5092316553/jobs/9153505343
=> [350] Mask ARM secrets in cluster pipeline

.github/workflows/deploy-cluster.yml
Fix pipeline failure: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/5092514537/jobs/9167577065
Use the powershell syntax to add the variables to the environment
=> [350] Fix ARM variables in DNS terraform

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Add namespaces for GIT migration
Updated test, dev and prod vars to include the new get-into-teaching namespaces
make env terraform-apply
NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml
=> Add GIT Namespaces

scripts/konduit.sh
We need this to support restoring a database using Postgres's custom database dump format which is faster and more flexible.
=> Add pg_restore support to konduit.sh

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Add namespaces for CPD to test and prod clusters
cpd-production (prod cluster)
cpd-test (test cluster)
cpd-development (test cluster)
=> Add namespaces for CPD

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
SRTL stands for: Support and Reward Teachers and Leaders The division support claims and the teacher pay calculator
The list was reordered alphabetically and should be kept ordered
=> [448] SRTL namespaces

cluster/terraform_aks_cluster/config/platform-test.tfvars.json
Upgrade the platform test environment to version 1.26.3
=> 334-Kubernetes-version-upgrade-12.6

cluster/terraform_aks_cluster/config/development.tfvars.json
334-Dev-Cluster upgrade to 1.26.3
=> 334-Dev-Cluster upgrade to 1.26.3

README.md, documentation/public-ips.md
Document update to list production and test cluster public IPS
=> 502 Public IP doc update

cluster/terraform_aks_cluster/config/production.tfvars.json
Upgrade the production cluster to 1.26.3
=> 334 Upgrade Production Cluster to 1.26.3

cluster/terraform_kubernetes/config/platform-test.tfvars.json
Upgrade Ingress Helm release to 4.7.1 for platform test
=> 509-Upgrade Ingress Helm release to 4.7.1

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the teaching vacancy paramemter to create namespace 
How to review
cd teacher-services-cloud
make terraform-kubernetes-init VERBOSE=1 CONFIRM_TEST=yes
terraform-kubernetes-plan VERBOSE=1 CONFIRM_TEST=yes
=> Adding the teaching vacancy paramemter to create namespace 

templates/new_service/terraform/application/database.tf
**Context**
add redis to service template
Added redis resource code to existing database code
cp -r new_service <destination_directory>
=> Added Redis to new service template

cluster/terraform_kubernetes/config/production.tfvars.json
Upgrade production ingress controller to version 4.7.1
=> 509-Upgrade production ingress controller

documentation/Ingress-controller-upgrade.md, documentation/aks-upgrade.md
Upgrade Monitoring Documentation update
=> Upgrade Monitoring Documentation update

documentation/onboard-service.md
Add Azure credentials process to new service onboarding
=> [551] Document Azure credentials for Github actions

.github/workflows/check_sp.yml, documentation/slack-webhook-integration.md
This is to check for service principle expiry
and send a notification on slack
=> Add service principle check

templates/new_service/Makefile, templates/new_service/terraform/domains/infrastructure/config/zones_Terrafile
=> Small tweaks to DNS and help

templates/new_service/Makefile
Keep adding to new_service template
Add make bin/konduit.sh
Same as https://github.com/DFE-Digital/find-a-lost-trn/blob/main/Makefile#L95
=> [559] Add make bin/konduit.sh to new_service template

cluster/terraform_aks_cluster/config/development.tfvars.json
trello : https://trello.com/c/yPcl69Ll
Upgrading Kubernetes version 1.26.6 on dev.
development tfvar updated version from 1.26.3 to 1.26.6
development tfvar updated version from 1.26.3 to 1.26.6
NA
NA
=>  Dev AKS version upgraded to 1.26.6

cluster/terraform_aks_cluster/config/test.tfvars.json
So we can take advantage of Kubernetes' new release and prevent compatibility issue, we are upgrading the kubernetes version
Update kubernetes version to "1.26.6"
=> Upgrade test env aks version

documentation/developer-onboarding.md
Help developers onboard to the platform and troubleshoot their apps
Refactor developer doc and add instructions for logging
Read doc and test commands
=> [632] Add logging to developer onboarding doc

.github/workflows/deploy-cluster.yml
Fix for failed Update DNS stage  https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/7044863532/job/19173929889
Terraform version updated to 1.6.4 in in Update DNS domains
=> Update DNS Domain stage terraform version updated to 1.6.4

documentation/onboard-service.md, documentation/production-checklist.md
Document best practices for production environments
Read the new documentation, check content and formatting (use view file to see the rendered mardown)
=> [617] Production checklist

.github/actions/deploy-environment/action.yml, .github/workflows/deploy-cluster.yml, cluster/terraform_aks_cluster/terraform.tf, cluster/terraform_aks_cluster/variables.tf, cluster/terraform_kubernetes/output.tf, cluster/terraform_kubernetes/terraform.tf, cluster/terraform_kubernetes/variables.tf, custom_domains/terraform/infrastructure/terraform.tf, custom_domains/terraform/infrastructure/variables.tf, templates/new_service/Makefile, templates/new_service/terraform/application/terraform.tf, templates/new_service/terraform/application/variables.tf
Implement improvements collected over time
- Remove azure credential variables from terraform
- Output welcome app URL
- Remove azure credentials from new service template
- Add terraform destroy to new service template
Simulated with terraform plan: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/7142712573
=> [817] New service template improvements

templates/new_service/Makefile
Passed environment value in make for review.
Added :  	$(eval export TF_VAR_environment=${ENVIRONMENT})
make review terraform-plan PR_NUMBER=123 is success.
=> Passed environment value  i.e TF_VAR_environment  for review

documentation/onboard-form-template.md, documentation/onboard-service.md
To facilitate smooth onboarding by capturing the usual tasks done HOW By creating a form to be completed for onboarding
added md document to be completed whilst onboarding
=> Added onboarding form /template

README.md, custom_domains/terraform/infrastructure/main.tf
So the code can be testing with the certificate changes on terraform module pre-release
Point the terraform module source to testing
=> Point the terraform module source to testing

README.md
Following the recent generation of new certificates for TeacherServices.Cloud(which is hosted in AKS) using GlobalSign; we need to document the steps involved for future use
Update readme within the Cluster TLS section, to include the steps for certificate generation, using GlobalSign
=> Update cluster TLS certificate process for Globalsign

documentation/postgres-faq.md
Add documentation on how to change the Postgres admin password
Postgres FAQ added to documentation folder
Read the doc
Can be tested on a review app for any service that uses the Postgres module
=> Add postgres password change doc

documentation/postgres-faq.md
Capture these parameters are they were useful during the teaching vacancies outage.
Add to the postgres FAQ
Try the settings. The query store and troubleshooting should become available.
=> [939] Document enhanced postgres monitoring

documentation/production-checklist.md
Improve onboarding process
Add to documentation
Check new section and linked Sharepoint page
=> [829] Document service offering creation

cluster/terraform_aks_cluster/config/test.tfvars.json, documentation/developer-onboarding.md
Migrate AKS clusters to Azure RBAC. This PR enables it on the *test* cluster.
Enable RBAC via test environment configuration
This has already been applied manually. Try connecting with kubectl following the developer onboarding documentation.
Apply manually first
=> [932] Migrate the test cluster to Azure RBAC

documentation/onboard-service.md
Document update done to use right terraform version
Onboard document update
Onboard document update
=> Onboard document updated done for terraform action

cluster/terraform_aks_cluster/config/production.tfvars.json
Upgrade all cluster to 1.27.7 , dev ,platform-test,test already upgraded , now production completed. 
AKS version upgraded to 1.27.7 for production.
There should be no changes for all terraform apply actions.
=> AKS Version 1.27.7 upgrade to production

.github/actions/deploy-environment/action.yml
Updated version azure/setup-kubectl  to V4.0.0
Upgraded the latest version for azure/setup-kubectl 
Warning should not generate.
=> Updated azure/setup-kubectl version 4.0.0

cluster/terraform_aks_cluster/config/production.tfvars.json, documentation/developer-onboarding.md
Enable Azure RBAC on the production cluster, just like we did on the other cluters
- Enable Azure RBAC
- Update documentation
Compare with other cluster configurations
Apply manually
=> [844] Migrate production cluster to Azure RBAC

cluster/terraform_kubernetes/config/prometheus/datasources.yaml, cluster/terraform_kubernetes/grafana.tf, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md, scripts/pfwd.sh
Create grafana service
- Create grafana service
- Apply change to dev(cluster 6) and platform test
- Create admin username and password and then save in keyvault
- Pull this branch to your local
- Connect to the applicable cluster using kubectl
- Set up port forwarding  using [kubectl -n monitoring port-forward service/grafana 3000:3000] - to test the grafana UI locally
https://trello.com/c/BgdHzhHE/1604-create-grafana-service
=> 1604 create grafana service

Makefile
=> Fix terrafile

scripts/konduit.sh
Failure when using a non admin permissions:
```
Error from server (Forbidden): deployments.apps is forbidden: User "14499d34-b1e7-4699-87fd-f0ea3f5e0c76" cannot list resource "deployments" in API group "apps" at the cluster scope: User does not have access to the resource in Azure. Update role assignment to allow access.
Error from server (Forbidden): deployments.apps "register-qa" is forbidden: User "14499d34-b1e7-4699-87fd-f0ea3f5e0c76" cannot get resource "deployments" in API group "apps" in the namespace "default": User does not have access to the resource in Azure. Update role assignment to allow access.
Error: Container does not exist or connection cannot be established
```
The namespace detection relies on cluster admin persmission. Introduce a new "-n namespace" argument to choose …
=> [1681] Add namespace option to konduit

README.md, documentation/developer-onboarding.md, documentation/onboard-service.md
The new AD groups and the new process is in place, the documentation should be updated.
- Update developer onbboarding doc
- Update Readme about the AD groups creation
- Review github documentation
- Review linked Sharepoint documentation
=> [843] Update documentation after AD groups change

cluster/terraform_kubernetes/prometheus.tf, documentation/monitoring.md
Typo fix and documentation updated with more information.
Typo fix and documentation updated with more information.
Added documentation how to check user and password details
=>  Typo fix  secrets and amendend document how to check scretes

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/rO6NTNwx/1700-create-alerts-for-all-services
Added monitoring for Register service 
added register to the list of alertable apps in config
exec into a register pod
stress the pod by running stress-ng
=> Added monitoring for Register service

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/rO6NTNwx/1700-create-alerts-for-all-services
Added school experience alerts
added entries for school experience in the alertable apps
=> school experience alerts

cluster/terraform_kubernetes/config/production.tfvars.json
=> Create alerts for faltrn prod

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/rO6NTNwx/1700-create-alerts-for-all-services
Added monitoring for ITTMS
added ITTMS to the list of alertable apps in config
=> Added monitoring for ITTMS, CPD and Publish

cluster/terraform_kubernetes/filebeat.tf
https://trello.com/c/6yYlFmd6/1689-logging-reload-filebeat-on-config-change
Add config_map_hash to cause the filebeat pods to be redeployed if a change is made to filebeat.yml
make development terraform-apply ENVIRONMENT=clusterx
make development terraform-apply ENVIRONMENT=clusterx (no change)
update the yml
make development terraform-apply ENVIRONMENT=clusterx (should redeploy the filebeat pods)
=> Add config map hash to restart pods on yml change

documentation/onboard-service.md
We want to make it easier to create/configure domains for services
Update the Custom Domains area in onboard-service.md
=> Update custom domains

documentation/onboard-service.md, documentation/production-checklist.md, templates/new_service.sh, templates/new_service/terraform/application/config/production.tfvars.json
StatusCake was refactored with the use of the infra team contact group
- Update the onboarding documentation
- Update the new_service template
- Review the documentation
- Run the template: https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/onboard-service.md#generate-code and observe the change
=> [1654] Update StatusCake in documentation and template

README.md, documentation/aks-logs.md, documentation/logit-io.md
Logit.io has been implemented and should be documented
Add markdown documentation
Read and see if it makes sense from an infra engineer point of view
=> [1685] Add Logit.io documentation

cluster/terraform_kubernetes/config/dashboards/nginx-ingress-controller.json, cluster/terraform_kubernetes/grafana.tf
Added Ingress Controller Dashboard
New dashboard added to grafana.
Deployed on dev Cluster : https://grafana.cluster3.development.teacherservices.cloud/d/nginx/nginx-ingress-controller?orgId=1&refresh=5s
=> Added ngnix dashboard

documentation/aks-upgrade.md
Updated AKS Upgrade document with kubectl version step
Updated AKS Upgrade document with kubectl version step.
Review AKS Upgrade document
=> Updated AKS Upgrade document with kubectl version step

cluster/terraform_kubernetes/alertmanager.tf, cluster/terraform_kubernetes/filebeat.tf, cluster/terraform_kubernetes/grafana.tf, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/thanos.tf, cluster/terraform_kubernetes/variables.tf, cluster/terraform_kubernetes/welcome_app.tf
Building a dev cluster sometimes cause transient errors
Fix some dependencies
Run terraform-kubernetes-apply. It should work the first time.
=> [1821] Fix cluster build errors

documentation/developer-onboarding.md
WHY: to enable the dev teams understand the process better
HOW: By updating the md file
Added the monitoring URLs and the procedure for creating dashboards
added the descriptions to the md file
check md file that it meets requirements
=> Added documentation for monitoring

cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_aks_cluster/config/platform-test.tfvars.json, cluster/terraform_aks_cluster/config/test.tfvars.json
Upgraded all clusters to 1.27.9,  dev , platform-test, test.
AKS version upgraded to 1.27.9
Execute following command to verify the cluster version in output (expected value : Server Version: v1.27.9)
kubectl version
Pipeline should success with out any issues.
=> AKS Version Upgraded to 1.27.9

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/output.tf, cluster/terraform_kubernetes/variables.tf, cluster/terraform_kubernetes/welcome_app.tf, documentation/logit-io.md
Ship logs to Logit.io and decode them so we can observe HTTP traffic
- Enable logging using annotations
- Update logstash filter documentation
- Deploy welcome app by default (useful for testing)
- Use the welcome app and fake front door domain: https://review-colin.apply-for-teacher-training.service.gov.uk/
- Check the logs in Logit.io are there and decoded
Update the logstash filter in all the stacks
- Check the Logit.io stacks are sized appropriately
- Reindex patterns
=> [1694] Ship ingress nginx logs to Logit.io

documentation/logit-io.md
Add more details
- logstash inputs
- mapping conflicts
- delete extra indices
Review the documentation (use `View file` to see the formatting)
=> [1694] Update logit.io documentation

cluster/terraform_kubernetes/config/test.tfvars.json
Created namespace srtl-test on the test cluster
Created namespace srtl-test on the test cluster.
After deploying  verify namesapce created  successcully on test cluster :  kubectl get ns
=> Created namespace srtl-test on the test cluster

documentation/maintenance-page.md
We need to update the maintenance template so it is easier to follow for implementation on services
- Update workflow bit in the docs
=> Update maintenance page template

documentation/logit-io.md
Standardise logging fields : https://trello.com/c/AqSayzVB/1813-standardise-logging-fields.
Lostsah config update for rename fields
Changes deployed on dev cluster
https://kibana-uk1.logit.io/s/edc08c51-a280-42fa-908d-c0c52f3ad508/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!t,sort:!()),metadata:(indexPattern:'8ac115c0-aac1-11e8-88ea-0383c11b333a',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-5m,to:now))&_q=(filters:!(),query:(language:kuery,query:''))
=> Lostsah config update for rename fields

cluster/terraform_aks_cluster/config/test.tfvars.json
AKS Upgrade 1.28.9 on test cluster
Test cluster upgraded.
Verify   test cluster already upgraded check using 'kubectl get node' .
pipeline should run successfuly.
=> AKS Upgrade 1.28.9 on test cluster

cluster/terraform_aks_cluster/config/production.tfvars.json, documentation/aks-upgrade.md
AKS Upgrade 1.28.9 on production cluster
production  cluster upgraded.
Verify production  cluster already upgraded check using 'kubectl get node' .
pipeline should run successfuly.
=>  AKS version upgrade 1.28.9 to production

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Thanos store and compactor need more memory
Increase memory allocation in tfvars.json
=> Increase thanos memory

documentation/production-checklist.md
Improve content in production checklist
Review content
=> [1914] Review production checklist

scripts/konduit.sh
The change introduced with the database name override created 2 bugs:
- it didn't work when the postgres URL contains options such as ?sslmode=require
- it got the wrong database name in case it had an underscore
See error: https://github.com/DFE-Digital/schools-experience/actions/runs/9984009145
Add a new parameter -b to override the database name, fix the regular expression and leave the original -d option unchanged
See success run in school experience: https://github.com/DFE-Digital/schools-experience/actions/runs/10011107735/job/27673808644
=> [1937] Fix konduit when using keyvault

documentation/frontdoor-certificate-revalidation.md
We need to document the process of revalidating Front door certificate, so it is easier to respond to related alerts
Outline the steps involved in revalidatingFront door certificate
Ensure the outlined steps are clear and can be followed by anyone
=> Document Front door certificate revalidation

scripts/konduit.sh
Update konduit to allow access to a database via a separately deployed app
Add "-x" option to konduit.sh
scripts/konduit.sh -x register-qa -- psql
scripts/konduit.sh -x -r REDIS_QUEUE_URL register-qa -- redis-cli
remove extra debugging output
=> Allow konduit to connect via a separate deployment

documentation/logit-io.md
Some of logs  for  deployment ingress-nginx-controller   not parsing , due to parsing pattern not matching
Adding matching expression for multiple patterns
Verify logs on logit.io where logs start with ip adress and log level , it should parse properly.
NA
Need to apply into all the environments.
=> Fixed parsing issues

cluster/terraform_kubernetes/config/production.tfvars.json
Grafana dashboard is showing 'No data'
We need to increase the memory for prometheus
=> Revert prometheus CPU

documentation/production-checklist.md, documentation/rebuild-cluster.md
Delete locks were added to protect critical resources
Document process around locks
Review doc content
=> [1894] Document Azure resource delete locks

README.md, documentation/disaster-recovery-testing.md, documentation/disaster-recovery.md
Adding documentation for DR and running a DR test for a service on AKS
https://trello.com/c/WoMjIGvG/1862-dr-document-dr-test-processes 
Add documents
Read documents. Are they helpful in case of a DR scenario? And to run a DR test?
=> Add DR testing document

scripts/konduit.sh
https://trello.com/c/4RyOYxPm/1971-fix-konduit-x-overrides
konduit with -x (separate pod) ignores some of the other options 
Update script so that -x can be used with -k, -u, etc
connect to register-qa db via register-qa
`scripts/konduit.sh register-qa -- psql`
connect to register-qa db via separate pod
`scripts/konduit.sh -x register-qa -- psql`
connect to sqlpad-qa db via register-qa (using kv secret)
`scripts/konduit.sh -k s189t01-sqlpad-qa-kv -d sqlpad-qa register-qa -- psql`
connect to sqlpad-qa via separate pod (using kv secret)
`scripts/konduit.sh -x -k s189t01-sqlpad-qa-kv -d sqlpad-qa register-qa -- psql`
connect to url db via register-qa
`scripts/konduit.sh -u 'some-complete-url' register-qa -- psql`
connect to url db via separate pod
`scripts/konduit.sh -x -u …
=> Allow all options for konduit via a separate pod

scripts/konduit.sh
https://trello.com/c/Zkl78tQ5/1977-backup-ptr-database-using-github-action 
Add postgres server-name override for konduit, so we can take a backup of a PTR server in a DR situation
Add -s option to override the Postgres server name
For dev cluster6
connect to main db, s189d01-rtt-rv-pg (run /dt to see tables)
`scripts/konduit.sh -x register-rm1 -- psql`
connect to PTR db (run /dt to see tables)
`scripts/konduit.sh -x -s s189d01-rtt-rv-pg-ptr register-rm1 -- psql`
=> Add postgres server-name override for konduit

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
We need to provide access from these namespaces within the kubernetes cluster to communicate with GCP BigQuery
Will create a serviceaccount for each namespace aswell as the azurerm_user_assigned_identity.gcp_wif for identity federation.
Have ran a Terraform plan against a test cluster to validate there are no breaking changes.
=> Adding WIF namespaces for GIT

documentation/disaster-recovery-testing.md
https://trello.com/c/Q60Q1OZq/1984-dr-test-template
Add DR test template to documentation
Add template and links to documentation
Check template and doc updates
=> Add DR test template to DR testing doc

templates/new_service/maintenance_page/Dockerfile, templates/new_service/maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl, templates/new_service/maintenance_page/manifests/maintenance/service_maintenance.yml, templates/new_service/maintenance_page/nginx.conf, templates/new_service/maintenance_page/scripts/failback.sh, templates/new_service/maintenance_page/scripts/failover.sh
Template fixes for the maintenance page template
- add nginx-unprivileged image, and associated port & path changes
- update tfvars path to application/config
- change failback.sh to 755 permissions
Check files
=> Maintenance page template updates

documentation/maintenance-page.md
Update maintenance page to include updating DSI config with temp ingress
documentation update
Check it makes sense
=> Add DSI note for maint page temp ingress

documentation/Ingress-controller-upgrade.md
There is a typo and misleading information in the ingress controller upgrade documentation
- Update "life cucle below" to "life cycle below"
- Update the text in the 24 hours wait after success deployment to test environments bit
=> Update ingress controller upgrade documentation

cluster/terraform_kubernetes/variables.tf
Ingress default version is not up-to-date
Set ingress default version to 4.11.0
=> Update ingress default version

documentation/disaster-recovery-testing.md, documentation/disaster-recovery.md, documentation/maintenance-page.md
DR documentation updates resulting from the recent DR test.
https://trello.com/c/M8apVWh5/2009-dr-test-documentation-updates
Various modifications and additions to improve the process 
Read through changes and check they make sense
=> DR documentation updates

cluster/terraform_kubernetes/config/production.tfvars.json
Revert ingress  ngnix version to 4.8.3
Revert ingress  ngnix version to 4.8.3
Tested on plat-test and test
=> Revert  ngnix version to 4.8.3

cluster/terraform_aks_cluster/.terraform.lock.hcl, cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_kubernetes/.terraform.lock.hcl
Updated AKS version to 1.29.7
Updating dev node pools to aks version 1.29.7
Can deploy a review app to the cluster and validate healthcheck
=> Changes to AKS clusters v 1.29.7

documentation/disaster-recovery-testing.md
A few changes after the recent DR test
- add prereq for an app url that shows the current image tag sha
- add note to check for any postgres diagnostics settings after deleting the postgres server
Updates to DR testing documentation
Check changes
=> Update DR testing documentation

templates/new_service/Makefile, templates/new_service/terraform/application/config/development.tfvars.json, templates/new_service/terraform/application/config/production.tfvars.json
Improvements to the new service templating and makefile definitions
Get rid of some default tfvar variables aswell as adding clarity in the make target definition for non review environments by removing the environment definition in tfvars.
Run the make new_service templater to check the corrected values if desired.
=> 1999 new service template improvements

.github/actions/deploy-environment/action.yml
Updated actions to use shared kubectl action
Updated actions to use shared kubectl action
=> Updated pipeline to use shared action

templates/new_service/terraform/application/database.tf
We need to update postgres version to the latest stable one
Change postgres version to 16
https://trello.com/c/4PBO6Miu/834-change-default-postgres-version-to-16
=> Change default postgres version to 16

documentation/disaster-recovery-testing.md, documentation/disaster-recovery.md
During the TRS DR test it was identified that workflow names were not consistent
- Update workflow names in DR docs
- Minor documentation tweaks
Workflows should match TRS ones: https://github.com/DFE-Digital/teaching-record-system/pull/1554
=> [2034] Standardise DR workflow names

documentation/logit-io.md
https://trello.com/c/VYI4c1aF/1926-add-logit-stack-monitoring
Add monitoring and alerting for Logit stack logs information to Logit documentation..
- too many logs received by logit
- no logs received
Added details to Logit documentation
Read doc
=> Add logit monitoring and alerting doc

documentation/developer-onboarding.md
add tips for az login
document issues using az login during onboarding
adding a few extra docs for developer onboarding as part of incremental improvement
it also picked up a few lines endings issues. 
check my info about using azure portal is correct.
=> add tips for az login

documentation/onboard-service.md, templates/new_service/Makefile, templates/new_service/terraform/application/application.tf, templates/new_service/terraform/application/config/development.yml, templates/new_service/terraform/application/config/production.yml, templates/new_service/terraform/application/config/review.yml, templates/new_service/terraform/application/variables.tf
Add the yaml environment variable pattern to new_service template
- Add the terraform code and yaml files
- Update documentation
Compare with https://github.com/DFE-Digital/itt-mentor-services implementation
Review documentation
=> [2019] Add environment variable yaml files to newservice template

documentation/disaster-recovery.md
Making DR documentation clearer
Updating konduit commands with examples
=> Update DR documentation

documentation/onboard-service.md, documentation/production-checklist.md, templates/new_service/.github/workflows/build-and-deploy.yml, templates/new_service/.github/workflows/build-nocache.yml, templates/new_service/Makefile, templates/new_service/terraform/application/config/development.yml, templates/new_service/terraform/application/config/production.yml, templates/new_service/terraform/application/output.tf, templates/new_service/terraform/application/variables.tf
https://trello.com/c/pxhaHtuQ/2088-create-github-workflow-templates
Add github workflow templates for build-and-deploy and build-no-cache, that can be used when building a new service
Add templates
modify terraform output.tf for url
tbc
=> Add gh workflow templates for build and deploy

cluster/terraform_aks_cluster/config/production.tfvars.json
apps1 node pool has reached max size of 40 nodes
Increase to 50
=> Increase apps1 node pool from 40 to 50

documentation/aks-logs.md, documentation/developer-onboarding.md, documentation/production-checklist.md, templates/new_service/terraform/application/application.tf
Help developers
- 2FA configuration
- Move Azure logs doc
- Detail Logit.io for devs
- Enable Logit in template
Read documentation
=> [1955] Update developer onboarding doc

cluster/terraform_aks_cluster/variables.tf, cluster/terraform_kubernetes/variables.tf, templates/new_service/terraform/application/output.tf, templates/new_service/terraform/application/variables.tf, templates/new_service/terraform/domains/infrastructure/variables.tf
The tflint workflow job only reports on new code, so these linting errors were not shown
Fix linting issues, reported by tflint manually in each terraform directory
Run tflint in each terraform directory
=> [2158] Fix terraform linting issues

cluster/terraform_kubernetes/config/production.tfvars.json
RSM migration to AKS production environment
Add slack webhooks for notifications
Run the command `make production terraform-kubernetes-plan`
=> Enable RSM slack notifications

templates/new_service/.github/workflows/postgres-restore.yml
bug in postgres restore workflow 
fix confirm-production bug in postgres restore workflow 
see https://github.com/DFE-Digital/refer-serious-misconduct/pull/1264 for change in a repo and testing. 
[rsm: add workflow for aks database backup and restore](https://trello.com/c/YC6xGcSC/2156-rsm-add-workflow-for-aks-database-backup-and-restore)
=> fix confirm-production in postgres-restore template

documentation/onboard-service.md, documentation/production-checklist.md, templates/new_service/Makefile
Improve documentation around monitoring
- Update production checklist
- Add action-group make command
- Read documentation
- Try the tenmplate and action group command
=> [2161] Monitoring documentation

documentation/production-checklist.md
Broken links in doc
Fix links
Read doc and check links
=> Fix links in production checklist

documentation/onboard-form-template.md, documentation/onboard-service.md
Improve onboarding documentation
- Add domain name limit
- Include content from https://github.com/DFE-Digital/teacher-services-cloud/pull/103
Review documentation content and formatting
=> Onboarding documentation

cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_kubernetes/variables.tf, documentation/aks-upgrade.md
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality. Our clusters are currently on 1.29
Upgrade the Kubernetes cluster from 1.29.7 to 1.30.6.
development cluster configuration for kubernetes cluster, orchestrator version for all node pools from 1.29.7 to 1.30.6
=> Upgrade AKS from 1.29.7 to 1.30.6

cluster/terraform_kubernetes/config/production.tfvars.json, documentation/onboard-service.md
Configuration error in bat managed identity
- The name sould be "bat" and not "bat-production"
- Documentation update
Compare with the other environments
=> [2151] Fix bat managed identity name

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Managed identities for cpd are required to google enable federated auth
Add configuration for creating managed identities for cpd in test and production azure subscriptions
Check to see if the managed identities has been created in test.
https://trello.com/c/sIkKBrl0
=> Add gcp-wif managed identities for cpd

Makefile, README.md, cluster/terraform_kubernetes/config/production.tfvars.json, documentation/onboard-service.md, documentation/platform-faq.md, templates/new_service/Makefile
Simplify kubelogin configuration
Depends on https://github.com/DFE-Digital/github-actions/pull/106
- Make use of variable AAD_LOGIN_METHOD set by the [set-kubelogin-environment](https://github.com/DFE-Digital/github-actions/tree/master/set-kubelogin-environment) github action
- Also fix managed identity variable name for production
See https://github.com/DFE-Digital/itt-mentor-services/pull/1281
=> [2151] Update kubelogin makefile commands for OIDC

cluster/terraform_kubernetes/config/production.tfvars.json
Wrong configuration in GA WIF for ITTMS
Make it "itt-mentor-services" instead of ittms
Compare with test
=> [2151] Fix GA WIF ITTMS repository name

documentation/developer-onboarding.md
Action from retro to avoid security incidents
Link dev onboarding doc to the technnical guidance
Review documentation
=> [2151] Add data protection to dev onboarding doc

.github/actions/deploy-environment/action.yml, Makefile
Broken workflow: https://github.com/DFE-Digital/teacher-services-cloud/commit/a6aa722de67abc90dd5e06e487501abfc52f1d9c/checks
Remove unnecessary variables
Successful run: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/12694945020/job/35385833433
=> [2151] OIDC smoke test  - Fix workflow

.github/workflows/deploy-cluster.yml, documentation/platform-faq.md
Worflow failure: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/12695282451
- Add missing permissions block
- Update FAQ
Successful run: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/12708016032
=> [2151] Fix update domains job

documentation/platform-faq.md
Help troubleshooting OIDC error
Update platform FAQ with new OIDC error
Review documentation
=> [2151] Add subscription error to OIDC FAQ

templates/new_service/terraform/application/application.tf, templates/new_service/terraform/application/config/development.yml, templates/new_service/terraform/application/config/production.tfvars.json, templates/new_service/terraform/application/config/production.yml, templates/new_service/terraform/application/statuscake.tf, templates/new_service/terraform/application/variables.tf
Provide explicit apex URL for SSL monitoring
- Introduce apex_url terraform variable
- Remove EXTERNAL_URL environment variable
- Refactor applciation_configuration module to use config_variables_path
- Run make new_service command
- Successful validation: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/12748074050/job/35527469083?pr=348
=> [2203] Template external url

documentation/monitoring.md
There is a requirement to tune metrics retention.
https://trello.com/c/QpHjd0zN
Add metrics retention information to the monitoring documentation
Check the monitoring documentation section on this [link](https://github.com/DFE-Digital/teacher-services-cloud/blob/update_monitoring_docs/documentation/monitoring.md?plain=1#L161).
=> Add metrics retention documentation

cluster/terraform_kubernetes/welcome_app.tf, templates/new_service/maintenance_page/Dockerfile
nginxinc/nginx-unprivileged:1.26.1 has various vulnerabilities reported by SNYK
update version of nginx docker image in maintenance page template 
view change compare change to https://github.com/DFE-Digital/technical-guidance/pull/208/files for correctness 
https://trello.com/c/wz8QjkY5/2204-update-nginx-base-image
=> Update nginx base image in template

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Create wif resources for afqts to be used by github workflows
Add afqts envs to test and prod cluster tfvars
make test terraform-plan (already deployed manually)
=> Add ga wif for afqts

documentation/logit-io.md
Simplify docs and retention periods mentioned are incorrect
Removing docs with plan suggestion based on retention period.
=> feat: Removing retention period reference for planning in logit docs

.gitignore, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Moving CTP to OIDC workflows from Azure secrets
Adding terraform scaffolding to create managed identities with federated credentials for each environment for the CTP service repo.
You can validate this once the Terraform has ran by looking at the Azure Managed identities and validating it exists for CTP along with the federated credentials for each environment.
=> 2201 GitHub actions OIDC for all services

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Migrate childrens barred list  workflows to use OIDC
https://trello.com/c/FWUebqgi
Create federated credentials for childrens barred list for all environments
• Update workflows in childrens barred list
=> Add check childrens barred list to TRA managed identity

templates/new_service/maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
As per ITHC, set below for maintenance app deployment template
- allowPrivilegeEscalation: false
- runAsNonRoot: true
Update to template file
tested in GIT
=> security improvements for maintenance template

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Create federated credentials for Apply for teacher training workflows
Create federated credentials in test and production
Run terraform-plan in test and production
=> [2201] Apply for teacher training federated credentials

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the correct federated credentials namespaces for CAPT based on secrets within repo settings.
Adding the correct federated credentials namespaces for CAPT based on secrets within repo settings.
=> feat: Adding namespaces for CAPT

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding CPD to teacher services cloud
Adding CPD ECF namespaces
=> feat: Adding namespaces for CPD ECF

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Migrate schools experience workflows to use OIDC
https://trello.com/c/FWUebqgi/2201-github-actions-oidc-for-all-services
Create federated credentials for schools experience for all environments
• Update workflows in  schools experience
=> Create schools experience in GIT managed identity

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Add register-trainee-teachers managed identities
Update test and prod cluster tfvars.json
make test|production terraform-plan
=> Add register to managed identity

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
=> feat: Adding WIF for AYTQ

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Migrate get into teaching app workflows to use OIDC
https://trello.com/c/FWUebqgi
Create federated credentials for get into teaching app for all environments
• Update workflows in get into teaching app
=> Add get into teaching app to GIT managed identity

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Migrate refer serious misconduct workflows to use OIDC
Create federated credentials for refer serious misconduct for all environments
Review the federated credentials created in test environment
- Create secrets
- Update workflows in publish teacher training
=> Add rsm to tra managed identity

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Enable Github actions OIDC on TV
Create federated credentials for each TV environment
Run terraform plan
=> [2201] TV federated credentials for Github actions OIDC

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Migrate teaching school hub finder workflows to use OIDC
https://trello.com/c/FWUebqgi
Create federated credentials forteaching school hub finder for all environments
• Update workflows in teaching school hub finder
=> Add teaching school hub finder to CPD managed identity

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding WIF to FALTRN
Adding WIF to FALTRN
=> feat: Adding WIF for FALTRN

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding WIF for CPDNPQ
Adding WIF for CPDNPQ
=> feat: Adding OIDC for CPDNPQ

documentation/disaster-recovery.md
Updates to DR documentation after feedback from the Register DR test.
documentation updates
Check the changes are clear, and make sense.
=> Updates to DR documentation

README.md, documentation/production-checklist.md, documentation/slack-webhook-integration.md, templates/new_service/.github/workflows/backup-db.yml, templates/new_service/.github/workflows/build-and-deploy.yml
Bring improvements and simplify
- Fix concurrency
- Use Slack webhook from Github secrets to simplify workflow
- Document Slack webhook
- Compare with workflows we recently implemented
- Review documentation
=> [1972] Update template domains workflow

cluster/terraform_kubernetes/config/dashboards/review-apps.json, cluster/terraform_kubernetes/grafana.tf, cluster/terraform_kubernetes/variables.tf, documentation/aks-upgrade.md
Sow old review apps to help identify orphans
- Create Review apps Grafana dashvoard
- Document in AKS upgrade
Dashboard deployed to https://grafana.test.teacherservices.cloud/d/beft4p5nhnt34de/review-apps?refresh=5m&from=now-24h&to=now&var-NAMESPACE=All
=> [2295] Review apps dashboard

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Add GA wif resources for new service Find-Teachers-For-Research
Add FTR service envs to test and prod cluster tfvars
=> Add ga wif for new ftr service

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
For tech-docs and technical-guidance OIDC
Add managed identities and federated credentials
Run terraform-plan
=> [2279] common and tech-arch managed identities

cluster/terraform_kubernetes/config/production.tfvars.json
New environment for register
Add env to bat ga_wif_managed_id
=> Add register csv-sandbox env to ga oidc

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
A critical vulnerability CVE-2025-1974 in ingress-nginx needs to be fixed. 
https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974
Update the ingress-nginx helm chart to version 4.11.5 on development environments
Check the ingress (dev cluster)
| Service Name| URL|
|--------|----|
| Grafana | https://grafana.cluster1.development.teacherservices.cloud/ |
| Prometheus | https://prometheus.cluster1.development.teacherservices.cloud/ |
| Nginx landing page | https://www.cluster1.development.teacherservices.cloud/ |
Check the ingress (platform-test cluster)
| Service Name| URL|
|--------|----|
| Grafana | https://grafana.platform-test.teacherservices.cloud/  |
| Prometheus | https://prometheus.platform-test.teacherservices.cloud/ |
| Nginx landing page | …
=> Update nginx controller to 4.11.5

templates/new_service/.github/workflows/build-and-deploy.yml, templates/new_service/.github/workflows/delete-review-app.yml
some minor fixes after using the templates for a new service
changes to template workflows
Check code
Changes are running in Find-Teachers-For-Research
=> Some minor template workflow fixes

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Configure Register of training providers workflows to use OIDC
https://trello.com/c/Qs3GoLjP/2330-new-service-register-of-training-providers
Create federated credentials for Register of training providers for all environments
=> Add Register of training providers to BAT managed identity

cluster/terraform_kubernetes/config/test.tfvars.json
Necessary so that GA WIF has a mapping to the review environment for get-into-teaching-api service
Adding the review environment to GA WIF
Workflows for the review environment will authenticate
=> Add review environment for OIDC for git api service

documentation/production-checklist.md
Add rate limiting to production checklist
Update documentation
Read the new doc
=> Add rate limiting to production checklist

templates/new_service/.github/workflows/backup-db.yml, templates/new_service/.github/workflows/build-and-deploy.yml, templates/new_service/.github/workflows/delete-review-app.yml, templates/new_service/Makefile, templates/new_service/terraform/application/output.tf, templates/new_service/terraform/application/variables.tf, templates/new_service/terraform/domains/environment_domains/output.tf
The new service template to be updated as per the RoTP
Enhance the template code for new service based on RoTP service
RoTP PRs
=> Enhance the template code for new service

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Alerts configured for grafana, thanos for High Memory and CPU
Alerts configured for grafana, thanos for High Memory and CPU
Alerts available in Prometheus UI
=>  Alerts configured for grafana, thanos for High Memory and CPU

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the alertmanager receiver config for TECHDOCS
Adding the alertmanager receiver config for TECHDOCS
=> feat(2354): techdocs - update deployment monitoring

cluster/terraform_kubernetes/config/production.tfvars.json
Alerts configured for tech guidance for High Memory and CPU
Alerts configured for tech guidance for High Memory and CPU
Alerts available in Prometheus UI
=> Alerts configured for tech guidance for High Memory and CPU

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the new service test and production environments GA WIF
Check indentity has been created and reference client ID as secret in repo for pipeline roles to authenticate with.
=> Add get-ready-to-teach namespaces to GA WIF

documentation/production-checklist.md
Update rate_limit documentation in the production checklist to reflect upcoming changes
Update to production checklist
Read the doc
Depends on https://github.com/DFE-Digital/terraform-modules/pull/157
=> Update rate limiting doc

cluster/terraform_kubernetes/config/production.tfvars.json
https://trello.com/c/IMDb1djy/2354-update-deployment-monitoring
- implement deployment monitoring for hedgedoc
=> feat(2354): added deployment monitoring for hedgedoc

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/IMDb1djy/2354-update-deployment-monitoring
- add ingress-nginx-controller deployment monitoring
test envt:-
production:-
=> feat(2354): nginx - add deployment-monitoring

templates/new_service/.github/workflows/restore-deleted-postgres.yml
Adding the restore deleted postgres workflow template to new service
Adding the restore deleted postgres workflow template to new service
https://github.com/DFE-Digital/github-actions/pull/128
https://github.com/DFE-Digital/apply-for-teacher-training/pull/10929
=> Adding the restore deleted postgres workflow template to new service

documentation/postgres-upgrade.md, templates/new_service/Makefile
We don't have any documentation or guidance regarding Azure PostgreSQL database server major version upgrades.
Add documentation and some commands to the Makefile 
Read the documentation, try out the commands on a review app (scaling) or non prod server (server logs)
=> Add postgres upgrade instructions

cluster/terraform_kubernetes/config/production.tfvars.json
Need to add new environment for RECT
Adding parity_check to env list for ga_managed_wif_id list
Pipeline should successfully deploy with a managed identity for with a client ID (to be saved in GHA as a secret)
Validate pipelines for TCS succeed.
=> Add parity_check env for RECT

cluster/terraform_kubernetes/config/production.tfvars.json
There is a requirement for a new environment on trs.
This change adds ga wif configuration to allow pipelines to deploy to the new env.
Review the federated credentials created in production subcription
=> Add ga wif config for tps-sandbox

documentation/postgres-upgrade.md
Add analyze instructions to the Azure Postgresql upgrade procedure
Documentation update
Check the documentation
=> Add analyze instructions to postgres upgrade

cluster/terraform_kubernetes/config/test.tfvars.json
Onboard a new service sap-sector
Add github oidc configuration for test
Check the github oidc configuration in portal
=> Add githut oidc config for test

.ghcr_cache_images.yml
=> feat(2128): manage postgis in terraform module - update ghcr.io cache with postgis images
