terraform/config/development.tfvars.json, terraform/dns.tf, terraform/variables.tf
**Context**
For development clusters, we want to automatically add a cluster DNS record in the DNS zone on build.
It will only create an A record if the variables are not null.
i.e. cluster_dns_zone & cluster_dns_resource_group_name
- Add dns.tf for DNS terraform resources
- Add new variables to tfvars and variables.tf
make development terraform-plan ENVIRONMENT=cluster5
=> Create dev cluster dns a record

custom_domains/infrastructure/main.tf, custom_domains/infrastructure/variables.tf, custom_domains/infrastructure/workspace_variables/tscp.tfvars.json
**Context**
Add the "development" NS record to the prod DNS zone for delegation to the dev DNS zone
- Add ns_record resource to terraform 
- Add variables
make prod-domain domains-infra-plan
check the prod DNS zone for the NS record
=> Add development NS delegation record to prod DNS

Makefile, cluster/terraform/variables.tf, custom_domains/terraform/infrastructure/.terraform.lock.hcl, custom_domains/terraform/infrastructure/main.tf, custom_domains/terraform/infrastructure/workspace_variables/tscp.tfvars.json
We require a wildcarded DNS record for each cluster
- Modify terraform to support adding wildcarded record
- Add config for platform-test
This change will be applied by running `make prod-domain domains-infra-apply` locally.  Prior to that please review changes, they can be tested by running `make prod-domain domains-infra-plan` locally.
=> Add DNS variables to platform-test tfvars

custom_domains/terraform/infrastructure/workspace_variables/tscp.tfvars.json
We require a wildcarded DNS record for each cluster
- Add config for test
This change will be applied by running `make prod-domain domains-infra-apply` locally.  Prior to that please review changes, they can be tested by running `make prod-domain domains-infra-plan` locally.
=> Add dns test to production

.github/workflows/deploy-cluster.yml, Makefile, cluster/terraform/main.tf, cluster/terraform/variables.tf
In order to securely manage connectivity to Azure resources outside of AKS we need to control the network it's attached.  To avoid tightly coupling external resources to the cluster we need to manage that network independently of AKS.
- Adds a vNet with a default subnet that is connected to the AKS cluster default node pool
- Adds the option to create additional subnets with optional delegations
- Adds the option to create a private DNS zone for each subnet that is linked to the subnet
Other things to note:
- To support deploying optional subnets with DNS zones into the development environment I've had to conditionally set the name of those zones.  That logic now exists in two separate places in the terraform, this might become increasingly difficult to maintain over time and cause …
=> Pre-provision vNet for AKS with option to add additional subnets

custom_domains/terraform/infrastructure/workspace_variables/tscp.tfvars.json
Clusters have been destroyed and redeployed, new public IPs were created as a result
- Update A record DNS config in tscp.tfvars.json
- Add missing record for production (wildcard at root)
- Check terraform is valid with `make production domains-infra-plan DOMAINS_ID=tscp`
- Check that correct IP addresses are used
- Check that new config is correct for production
=> Updated A record values in tscp DNS config

scripts/konduit.sh
**Context**
We need a replacement for the PAAS conduit plugin, which enables connecting to a backing service.
We use this mainly for psql connections to postgres, and also backing up and restoring postgres databases.
A minor use case is to connect to a redis service with the redis-cli. 
While the script works for redis, it's only currently to a k8 deployed redis, and will be updated when the Azure redis backing service is available.
Add konduit.sh script which provides similar functionality for AKS services.
Either create a review app, or use apply-review-5678 in cluster s189t01-tsc-test-aks
1.  open psql session via app container (to default db)
`konduit.sh apply-review-5678 -- psql`
2. open psql session to 5678 db via …
=> Add conduit replacement for AKS

cluster/terraform/config/development.tfvars.json, cluster/terraform/config/platform-test.tfvars.json, cluster/terraform/config/production.tfvars.json, cluster/terraform/config/test.tfvars.json, cluster/terraform/main.tf, cluster/terraform/variables.tf
Added `applications` node pool with values to be inserted from each environments tfvars
Some values have been hard coded as they should be true regardless of environment.
Created new local variable for uk south availability zones (1,2,3).
Create a new auto scaling node pool named `applications`
Ensure the default node pool can stretch across all availability zones within uk south
Successful build: < to link here >
https://trello.com/c/12D34eAJ/107-run-apply-build-with-secrets-from-s189
=> add 'applications' node pool

custom_domains/terraform/infrastructure/workspace_variables/tscp.tfvars.json
Following the clusters rebuild, a new ingress IP was allocated for each cluster. The domains must be updated.
The change has already been applied. You should see the nginx empty page: https://aaa.teacherservices.cloud/
=> [195] Update ingress DNS for all clusters

scripts/konduit.sh
**Context**
Update konduit.sh script to allow passing sql commands to psql
Add $OTHERARGS to psql
./konduit.sh apply-qa -- psql -c '\dt'
=> Allow passing args to konduit psql

scripts/konduit.sh
Add quotes to the $OTHERARGS variable,
required for commands to be run successfully
=> Add quotes to OTHERARGS var

cluster/terraform/config/platform-test.tfvars.json, cluster/terraform/config/production.tfvars.json, cluster/terraform/config/test.tfvars.json, cluster/terraform/main.tf, cluster/terraform/statuscake/main.tf, cluster/terraform/statuscake/variables.tf, cluster/terraform/terraform.tf, cluster/terraform/variables.tf
Add statuscake monitors for persistent clusters,
i.e. test, platform-test and production
Monitors the /healthz endpoint every 60 seconds 
Also added contact group to statuscake,
and added required KV secrets
make env terraform-plan
also tested using dev cluster5. see Teacher-Services-AKS-Cluster-DEV5 in statuscake
=> Add statuscake monitor for persistent clusters

cluster/terraform/kubernetes-config/ingress_controller.tf
Outcome of the load tests: https://trello.com/c/ZQlq0Rdd
Apply with 8 replicas requires 2 ingress-nginx replicas using 100m CPU. 20 should be enough for a while.
Check replicas on cluster 3:
```
kubectl get pods
```
=> [81] Increase ingress-nginx replicas to 20

README.md, cluster/terraform/.terraform.lock.hcl, cluster/terraform/aks-cluster/analytics.tf, cluster/terraform/aks-cluster/main.tf, documentation/aks-logs.md
We need to keep system logs to troubleshoot issues and incidents.
Log analytics is default on AKS. Diagnostic logs must be enabled and maybe container insights. We should implement it via terraform for platform-test, test and production clusters.
This is an initial implementation and may be refined later. The cost should be kept minimal.
Check for the changes in the diagnostics settings are set in cluster 1
for example ..
Kubernetes API Server should have a check mark enabled
In the Logs please run this kql query
```
AzureDiagnostics
| where Category == "kube-apiserver"
```
=> [207] Capture AKS system logs into a log analytics workspace

cluster/terraform_aks_cluster/config/test.tfvars.json
Increase Test cluster applications nodepool maximum size from 10 to 20
Due to currently hitting the maximum of 10 and unable to deploy new apps or update existing
=> Increase Test cluster app nodepool max size to 20

cluster/terraform_aks_cluster/config/production.tfvars.json
**Context**
The apply service was failing to deploy due to the node count set to 10. 
Apply service needed to resources than were available in the cluster.
**Changes proposed**
- Increase the node count to 20
=> Change max node count to 20

cluster/terraform_aks_cluster/.terraform.lock.hcl, cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_aks_cluster/config/platform-test.tfvars.json, cluster/terraform_aks_cluster/config/production.tfvars.json, cluster/terraform_aks_cluster/config/test.tfvars.json, cluster/terraform_aks_cluster/main.tf, cluster/terraform_aks_cluster/variables.tf, cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/ingress_controller.tf
We need a way to change the VM size of a new cluster.
We also need a process to move existing workloads from one cluster to another if we wanted to move to a node pool with bigger VM's.
Add code to support changing the VM size of a node pool from the `tfvars.json` file.
Add code to support adding labels to a node pool from the `tfvars.json` file.
1. Deploy the cluster to add the label to the existing node and deploy a new node with the new label
2. Deploy any applications running on the existing cluster ensuring their node selector uses the new label
3. Migrate the workloads to the new node
a) Disable autoscaling on the existing node
b) Cordon the existing nodes in the existing node pool
c) Drain the existing node - this should drain and move the existing workloads to the new node pool
d) …
=> Code to support node labels and node VM sizes

cluster/terraform_aks_cluster/config/platform-test.tfvars.json, cluster/terraform_aks_cluster/config/production.tfvars.json, cluster/terraform_aks_cluster/config/test.tfvars.json
We have changed the label used by the node selector so that it isn't specific to the node pool (e.g. agentpool), but can be a label which is added to multiple node pools (e.g. a custom label).
Remove the nodes which are no longer required
=> Remove old node pools

Makefile, cluster/terraform_aks_cluster/output.tf
Fix an issue when running terraform plan when there is no cluster created. The terraform_kubernetes terraform apply requires the cluster to exist or fails.
This now checks the cluster exists by checking the output from terraform_aks_cluster before running terraform_kubernetes.
Run with no cluster. You should get `make: *** [check-cluster-exists] Error 1` but no terraform plan error.
=> check-cluster-exists make command

Makefile, cluster/terraform_aks_cluster/config/development.tfvars.json, documentation/node-pool-migration.md
When we add a new node pool to a cluster we may want to move workloads from an existing node pool to the new one.
- Add some basic commands to the `Makefile` to make this process easier, more reliable and repeatable
- Add documentation to support the process
=> Add commands to help migrate pods to a new node

README.md, cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_aks_cluster/config/platform-test.tfvars.json, cluster/terraform_aks_cluster/config/production.tfvars.json, cluster/terraform_aks_cluster/config/test.tfvars.json, cluster/terraform_aks_cluster/main.tf, cluster/terraform_aks_cluster/variables.tf, documentation/aks-upgrade.md
**Context**
To be able to carry out a cluster and node upgrade using Terraform. 
**Changes proposed**
- Add parameter kubernetes_version - This sets the cluster version
- Add parameter orchestrator_version - This sets the version for the default node pool and the application node pools. 
- Provide guidance about the upgrade process, including the auto-upgrade feature
**Documentation describing AKS upgrade considerations**
[AKS Upgrade Considerations](https://hackmd.cloudapps.digital/Aal84OmxQR67u7UaNL4Faw)
**Guidance for review**
cluster2 was deployed into the development environment. The following text describe the upgrade process.
**Cluster and Node Upgrade Process**
To deploy cluster2 into the development subscription, ran below command:
```make development terraform-apply …
```
=> Added cluster and node upgrade parameters

Makefile, README.md
Avoid human mistakes when running on command line by forcing a separate command line confirmation for each environment
Run: `make test terraform-plan`
It should only work with `CONFIRM_TEST=something`
=> [294] Confirm make commands to non-dev environments

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/tls.tf, cluster/terraform_kubernetes/variables.tf, cluster/terraform_kubernetes/welcome_app.tf
Review apps under *.test.teacherservices.cloud keep getting blocked when users are on the DfE network. This brings a number of fixes required for Palo Alto to trust the domains.
- Provide full certificate chain. This requires string manipulation as the certificate chain returned by the terraform data source is in the wrong order. See azurerm issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/21467
- Disable HTTP port
- Deploy websites on top domains
Already manually deployed to platform-test and test
Test in dev:
- Deploy a review app to cluster2 (such as https://apply-review-4231.cluster2.development.teacherservices.cloud/)
- Make sure you're on the DfE network
- Access immediately
- There should be no error
=> [261] Temporary certificate issue

scripts/konduit.sh
Small fix to allow konduit to work with the new terraform module naming standard
run against register resources using external module
run against apply resources not using external module
=> Fix konduit to work with module app naming

cluster/terraform_aks_cluster/main.tf, cluster/terraform_kubernetes/ingress_controller.tf, custom_domains/terraform/infrastructure/workspace_variables/tscp.tfvars.json
When the cluster is recreated, the public IP changes and the *teacherservices.cloud domain must be updated.
Instead, we could create the public IP via terraform and configure the ingress controller to use it. 
Same goes for Egress IP Address so this has also been switched to Azure Public IP Address. 
- Added new public ip resource to the ingress controller tf file
- Set the  load balancer ip for the ingress controller helm release to the new public ip 
- Added new Public IP Resource to the main cluster tf file 
- Set the network profile of the main cluster to use this new public ip for egress
- Updated DNS to reflect migrated IPs for ingress and egress for all environments
- Deploy the cluster in an environment like dev
- Deploy an app i.e. register 
- Confirm everything is working ; can …
=> 299 migrate to public ip addresses for ingress and egress

README.md, cluster/terraform_aks_cluster/main.tf, cluster/terraform_kubernetes/ingress_controller.tf
The egress public IP is currently deployed to the nodes resource group. This caused a circular dependency:
Egress public IP -> Nodes resource group -> AKS cluster -> Egress public IP
This blocked creating new dev clusters.
Creating in the pre-existing cluster resource group removes this dependency.
Deploy a dev cluster
Follow the process in https://hedgedoc.teacherservices.cloud/OeejNnlrQzWfcPQd6Cbjtw?edit to move the IPs manually and update the terraform state.
=> [426] Move public IPs to cluster resource group

cluster/terraform_aks_cluster/config/test.tfvars.json
Upgrade the current version of AKS test cluster to version 1.26.3
=> 334-upgrade-test-clusters-to-1.26.3

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/variables.tf
Update the Ingress Nginx helm charts to version 4.7.1. Add environment specific variables
Introduce the bump in version to Development Cluster
=> 509-update-ingress-nginx

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/lowpriority_app.tf, cluster/terraform_kubernetes/variables.tf, documentation/lowpriority-app.md
The lowpri-app deployment reserves cpu and memory on each replica (default x3) which will be preempted by any standard deployment when there is no immediately available space. The lowpri-app will then be redeployed when new nodes have been added by the cluster autoscaler. 
This should lessen the number of deployments that fail waiting for new nodes to be started when there is no immediately available capacity.
**Before merge,**
remove `"enable_lowpri_app": true` from development.tfvars.json
as this should only be enabled in dev clusters when testing
Lowpri-app deployed (3 replicas)
There are 5 nodes in the cluster, and none have more than 0.5 cpu available.
Now we submit a new default priority app register-pr-99rm that has a cpu requirement (request) of 1 cpu per replica (x3)
The …
=> Add low priority class and deployment

documentation/onboard-service.md, templates/new_service/Makefile
- new_service doc: arm resource make target names
- Fix new_service domains variables in Makefile
Follow the [documentation](https://github.com/DFE-Digital/teacher-services-cloud/blob/619-onboarding-new-service-fixes/documentation/onboard-service.md?plain=1)
=> [619] new_service template fixes

cluster/terraform_kubernetes/ingress_controller.tf
Git app generates a larger response header than nginx currently allows
Requests return 'upstream sent too big header while reading response header from upstream' in the nginx logs
Increase proxy-buffer-size from 8k to 24k
make test|platform-test|production terraform-plan CONFIRM_env=yes
Change has already been made manually in the test cluster
kubectl describe cm/ingress-nginx-controller
=> Increase proxy-buffer-size from 8k to 24k for git

cluster/terraform_aks_cluster/analytics.tf
Terraform Apply is failing , due to deprication of retention_policy under aks_systems_logs
Removing retention_policy under azurerm_monitor_diagnostic_setting
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#retention_policy
=> Removed retention policy under azurerm_monitor_diagnostic_setting

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Changes related to Technical Guidence migration to AKS.
Creating New name spaces for Technical Guidence.
=>  Added new name spaces for techinical migration

templates/new_service/.gitignore, templates/new_service/Makefile, templates/new_service/terraform/application/config/development_Terrafile, templates/new_service/terraform/application/config/production_Terrafile, templates/new_service/terraform/application/database.tf, templates/new_service/terraform/application/output.tf, templates/new_service/terraform/domains/infrastructure/config/zones.tfvars.json
Improve new service template for little issues we collected over time
- use appropriate terraform-module tags
- Fix Makefile domains comments
- add bin/konduit.sh to .gitignore
- remove dmarc TXT record
- Pin Redis version to 6
- use module.web_application url output
Run the template as per the onboar service doc
=> [692] New service template improvements

cluster/terraform_aks_cluster/config/platform-test.tfvars.json
platform test AKS version upgraded to 1.26.6
platform test AKS version upgraded to 1.26.6
-     - Changes has been applied on Platform-test .
-     -  Check Kubernetes version using the command  kubectl version | grep Server  it should return  Server Version: v1.26.6
-     - Check Nodes version using command `kubectl get nodes` VERSION column should return all nodes 'v1.26.6'
-     - Check liveness of ngnix endpoint   `curl -is https://www.platform-test.teacherservices.cloud/ | grep HTTP ` it should return HTTP status 200
NA
NA
=> platform test AKS version upgraded to 1.26.6

cluster/terraform_kubernetes/welcome_app.tf
Welcome app pod replicas to spread across multiple node / zone for high availability.
Added topology spread logic for zone and hostname
Changes has been deployed on platform test , This can be tested as below.
- Run the command below to display nodes and the welcome app. The welcome app should be distributed across various nodes
- kubectl get po -n infra -o json -l app=welcome-app | jq '.items[] | {name: .metadata.name, node: .spec.nodeName}' 
NA
NA
=> topology_spread_constraint added to welcome app

cluster/terraform_kubernetes/ingress_controller.tf
We are seeing some connection errors on TRS when using front door. Microsoft support said the keepalive to the backend must be more than 90s. It was 60s by default.
Set keepalive to 120s
Client header timeout must be increased as well or the connection is stopped
Run the script:
```shell
start=`date +%s`
echo -e "GET /  HTTP/1.1\r\nHost:www.cluster1.development.teacherservices.cloud\r\n\r\n" | openssl s_client -connect www.cluster1.development.teacherservices.cloud:443 -servername www.cluster1.development.teacherservices.cloud -ign_eof
end=`date +%s`
runtime=$((end-start))
echo "KeepAlive timeout is around $runtime seconds"
echo "done"
```
It should show about 2min
=> [775] Increase ingress-nginx keepalive to 2 min

cluster/terraform_aks_cluster/config/production.tfvars.json, documentation/aks-upgrade.md
Upgrade production cluster from 1.26.3 to 1.26.6
Kubernetes Version to 1.26.6 , default node group to 1.26.6 and apps1 node group to 1.26.6
Upgrade is completed , this can be verified by using below commands.
-  Check Kubernetes version using the command  kubectl version | grep Server  it should return  Server Version: v1.26.6
-- Check Nodes version using command `kubectl get nodes` VERSION column should return all nodes 'v1.26.6'
=> Prod cluster upgraded to 1.26.6

cluster/terraform_aks_cluster/.terraform.lock.hcl, cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, documentation/Ingress-controller-upgrade.md
Upgrade helm chart Ingress NGNIX to 4.8.3
update the tfvars files to change the value to 4.8.3
make platform-test  terraform-apply  CONFIRM_PLATFORM_TEST=yes
=> Upgrade helm chart Ingress NGNIX to 4.8.3

cluster/terraform_aks_cluster/main.tf
A timeout error occurred whilst updating the node pools - it was found that default timeout is 60 minutes.
We need to allow enough time for updates to complete as well as provide enough time to investigate issues
Increase the timeouts for Create, Update and Delete to 180 minutes(3 hours) each
=> Increase terraform timeout on node pools

.github/workflows/check_sp.yml
The Slack message environment is missing.
`Please update the secret in **.`
Fixed in workflow check_sp
Slack message should display environment 
`  Please update the secret in *test*.`
=> Updated logic to populate environment in slack message

cluster/terraform_aks_cluster/config/platform-test.tfvars.json, cluster/terraform_aks_cluster/config/test.tfvars.json
1.26.10 is the next supported version. We should upgrade all clusters to next supported version
Update platform-test and test clusters to version 1.26.10
=> Upgrade aks cluster to 1.26.6 for test and platform-test

cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/UNWoI5f8/885-bug-deployments-are-timing-out-on-the-test-cluster
Increased min CPU for lowpriority app
Test tfvars Lowpriority app cpu requests increased from 0.1 to 0.5
Lowpriority app cpu requests increased from 0.1 to 0.5
=> Lowpriority app cpu requests increased from 0.1 to 0.2

cluster/terraform_aks_cluster/config/production.tfvars.json
1.26.10 is the next supported version. We should upgrade all clusters to next supported version
Upgrade production cluster to version 1.26.10
1. Connect to the production cluster by running the following make command(within the Teacher Services Cloud repo):
``` make production get-cluster-credentials CONFIRM_PRODUCTION=yes ```
1. Run the following kubectl command:
``` kubectl get nodes ```
The node versions should show: v1.26.10
=> Upgrade AKS cluster version to 1.26.10 for Prod

documentation/onboard-service.md
A simple change to the docs to make it a bit clearer on how to onboard. Targeted at PDM's, DM's, suppliers, those new to to Teacher Services as well as devs/tech leads etc.
=> added simple onboarding info to docs

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/l78negs6/910-create-monitoring-namespace
Monitoring namespace is needed before installing monitoring services for each cluster hence added 
to the cluster
add monitoring to namespaces entry
monitoring entry on tfvars files for each environment
=> Added monitoring namespace to all clusters

cluster/terraform_kubernetes/ingress_controller.tf
https://trello.com/c/y1REnkpz/797-add-resource-limits-for-ingress
Added requests and limits for ngnix  ingress controller 
1 ) Spin a new dev cluster : make development terraform plan ENVIRONMENT=clusterX
2 ) Execute :  kubectl  get deployment ingress-nginx-controller -o yaml and verify  limits set.
=> Added requests and limits for cpu and memory for ngnix controller

.github/actions/deploy-environment/action.yml, Makefile, cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_aks_cluster/config/platform-test.tfvars.json, cluster/terraform_aks_cluster/config/production.tfvars.json, cluster/terraform_aks_cluster/config/test.tfvars.json, cluster/terraform_aks_cluster/main.tf, cluster/terraform_aks_cluster/variables.tf, cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/terraform.tf, cluster/terraform_kubernetes/variables.tf, documentation/developer-onboarding.md, documentation/rebuild-cluster.md, scripts/export_aks_resources.sh, templates/new_service/Makefile, templates/new_service/terraform/application/terraform.tf
Migration of clusters to Azure RBAC. This enables it for the development cluster.
- Add option to enable Azure RBAC for each cluster
- Configure kubernetes and helm providers
- Update new service template
- Fix issues with cloning process
Build a new dev cluster using the new PIM set up
=> [925] Migrate development cluster to Azure RBAC

cluster/terraform_aks_cluster/.terraform.lock.hcl, cluster/terraform_aks_cluster/config/platform-test.tfvars.json, cluster/terraform_kubernetes/.terraform.lock.hcl
Migration of all clusters to Azure RBAC. This was applied manually on platform-test and tested.
Enable Azure RBAC on platform-test
- Check Azure RBAC is enabled
- Connect via kubectl
=> [931] Migrate the platform-test cluster to Azure RBAC

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/prometheus/development.prometheus.rules, cluster/terraform_kubernetes/config/prometheus/development.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/platform-test.prometheus.rules, cluster/terraform_kubernetes/config/prometheus/platform-test.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/production.prometheus.rules, cluster/terraform_kubernetes/config/prometheus/production.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/test.prometheus.rules, cluster/terraform_kubernetes/config/prometheus/test.prometheus.yml, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md, scripts/pfwd.sh
Add prometheus monitoring for non-prod clusters
Currently scrapes below metrics
- prometheus service
/metrics from the prometheus svc endpoint
- cadvisor 
/api/v1/nodes/${node}/proxy/metrics/cadvisor
- nodes 
/api/v1/nodes/${node}/proxy/metrics
- api server 
/metrics from the prometheus api endpoint
had to disable tls verify for it to work.
May need to think about if we want all of these metrics.
Can check node api metrics via kubectl get --raw /api/v1/nodes/${node}/proxy/metrics or /proxy/metrics/cadvisor
Alert rules, scrape configs, etc will be improved in later PR's.
Add required terraform resources
Add initial doc
make development terraform-plan ENVIRONMENT=cluster6
scripts/pfwd.sh
http://localhost:8080/
Remove "--storage.tsdb.retention.time=12h" from the prometheus deployment
=> Add prometheus

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/prometheus/development.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/platform-test.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/production.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/test.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/thanos.yml.tmpl, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/thanos.tf, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md, scripts/pfwd.sh
Add Thanos to prometheus monitoring.
Provides permanent backend storage.
https://trello.com/c/J1TkmCHm/1593-create-thanos-service
Create Azure storage account 
Add thanos sidecar to prometheus deployment
Add thanos services, querier, store-gateway, compactor
This has been manually deployed to all clusters.
make test terraform-plan CONFIRM_TEST=yes
./scripts/pfwd.sh
check thanos at http://localhost:8082
=> Thanos with sidecar

cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_kubernetes/.terraform.lock.hcl
https://trello.com/c/5FLQdnck/938-upgrade-clusters-to-kubernetes-1277
Dev Cluster upgrade from 1.26.10 to 1.27.7
Create  dev  cluster from  master, then update cluster following steps provided https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/aks-upgrade.md
=> Dev Cluster version Upgraded to 1.27.7

cluster/terraform_aks_cluster/config/platform-test.tfvars.json
https://trello.com/c/5FLQdnck/938-upgrade-clusters-to-kubernetes-1277
platform test Cluster upgrade from 1.26.10 to 1.27.7
Updated cluster following steps provided https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/aks-upgrade.md
=> Platform test AKS cluster upgraded to 1.27.7

cluster/terraform_kubernetes/config/prometheus/development.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/platform-test.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/production.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/test.prometheus.yml, cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/thanos.tf, cluster/terraform_kubernetes/variables.tf, cluster/terraform_kubernetes/welcome_app.tf
Thanos fixes
1. Some resources are failing due to a namespace dependency.
I couldn't find out why it suddenly started occurring, so have added a dependency in terraform.
e.g.
│ Error: Failed to create deployment: namespaces "monitoring" not found
│ 
│   with kubernetes_deployment.thanos-compactor,
│   on thanos.tf line 247, in resource "kubernetes_deployment" "thanos-compactor":
│  247: resource "kubernetes_deployment" "thanos-compactor" {
│ 
│ Error: Failed to create deployment: namespaces "infra" not found
│ 
│   with kubernetes_deployment.welcome_app[0],
│   on welcome_app.tf line 1, in resource "kubernetes_deployment" "welcome_app":
│    1: resource "kubernetes_deployment" "welcome_app" {
│ 
2. updated the dev cluster thanos storage account name, as it was using the same name for all …
=> Thanos fixes

.github/actions/deploy-environment/action.yml
Supress warnning in  pielines 
Upgraded the latest version for GitHub actions  Azure/login to 1.6.1 and azure/setup-kubectl to 4.0.0
Warning should not generate.
=> Upgraded to the latest version for GitHub actions azure/setup-kubectl to v4

cluster/terraform_kubernetes/config/prometheus/development.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/platform-test.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/production.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/test.prometheus.yml, cluster/terraform_kubernetes/kube_state_metrics.tf, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md
Trello Card:
https://trello.com/c/NHmSbfNc/929-configure-kube-state-metrics
Added Kube state metrics which is an important component of monitoring
added the terraform resources that will provision kube state metrics
make development terraform-kubernetes-apply  ENVIRONMENT=cluster3       
kubectl port-forward -n kube-system service/kube-state-metrics 8080:8080
curl localhost:8080/metrics
kubectl port-forward -n kube-system service/kube-state-metrics 8081:8081
curl localhost:8081/telemetry
=> Added Kube state metrics

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/thanos.tf, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md
https://trello.com/c/IbAu4gQD/1648-investigate-thanos-compactor-failure
Thanos compactor running out of memory on test and production clusters
Increase compactor memory to 2G
make test terraform-plan (no change as manually applied to test cluster)
=> Increase test/prod thanos-compactor memory to 2G

cluster/terraform_kubernetes/alertmanager.tf, cluster/terraform_kubernetes/config/prometheus/alertmanager-config.yaml, cluster/terraform_kubernetes/config/prometheus/alertmanager-slack.yaml, cluster/terraform_kubernetes/config/prometheus/development.prometheus.rules, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md, scripts/pfwd.sh
Create alert manager service on monitoring namespace.
Create alertmanager
Pull slack secret from azure key vault
1 )  deploy  any one-off dev cluster  example : cluster4  , ENVIRONMENT=cluster4
2 ) Do port-forward to check service is up and working kubectl -n monitoring port-forward service/alertmanager 8088:9093
3 ) check http://localhost:8088 , alert manager UI should come.
=> Create alermanager service

cluster/terraform_kubernetes/node_exporter.tf, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md
Add node exporter to prometheus monitoring
https://trello.com/c/LWrIjOPv/935-add-node-exporter
Add node-exporter daemonset
This creates a node-exporter pod on each node in the cluster
(currently deployed to dev cluster2)
make env deploy-plan
kubectl -n monitoring get pods (should be 1 node-exporter pod per node)
scripts/pfwd.sh
connect to prometheus and check for node_* metrics
=> Add node exporter for prometheus node metrics

cluster/terraform_kubernetes/ingress_controller.tf
https://trello.com/c/QZ7J2MX8/934-add-custom-metric-scraping
added ingress controller scraping by setting the podannotations
port forward the ingress controller pod and the prometheus pod
access the cluster 3 welcome page at https://www.cluster3.development.teacherservices.cloud/
notice the changes in the metrics shown eg 
promhttp_metric_handler_requests_total{code="200"} 34
nginx_ingress_controller_nginx_process_requests_total 
etc
=> Added ingress controller scraping

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Prometheus pod is failing with memory errors
https://trello.com/c/scNU7uh0/1674-increase-prometheus-memory
Increase memory from 2G to 3G
=> Increase prometheus memory to 3G

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Prometheus running out of memory
Increase memory from 3G to 4G for test and production clusters
=> Increase prometheus memory to 4G

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/thanos.tf, cluster/terraform_kubernetes/variables.tf, documentation/monitoring.md
Prometheus and thanos pods failing due to insufficient memory in test and prod clusters
Separate memory variables and Increase memory limits
Manually applied to pods to confirm they stop failures
=> Increase prometheus and thanos memory settings

cluster/terraform_kubernetes/config/production.tfvars.json
Production prometheus pod is crashlooping with Out of memeory
Bumped prometheus memory  to 8GB
Connect prod cluster and verify prometheus pod status  using command :  kubectl -n monitoring get po -l app=prometheus
the status should be Running.
=> Prometheus memory increased to fix CrashLoop

cluster/terraform_kubernetes/config/filebeat/filebeat.yml.tmpl, cluster/terraform_kubernetes/filebeat.tf, cluster/terraform_kubernetes/variables.tf, documentation/aks-logs.md
Enable filebeat to send logs to logit.io
It will send logs to logit if the container has annotation logit.io/send: true
Terraform updates
Deployed to cluster5, with app container sending logs to logit.io
make development terraform-plan ENVIRONMENT=cluster5
App deployed using terraform-modules branch 906-spike-application-log-shipping
=> Allow sending app logs to logit using filebeat

.gitignore, cluster/terraform_kubernetes/config/dashboards/k8s-views-pod.json, cluster/terraform_kubernetes/grafana.tf
Create a dashboard for the developers so they can see the health of their apps: CPU, memory, disk
-  Create a new dashboard k8s_views_pod
-  It should be possible to filter display by Namespace and Deployments in grafana
Currently deployed on cluster 6
=> 1658-grafana-application-health-dashboard

cluster/terraform_kubernetes/alertmanager.tf, cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/thanos.tf, documentation/monitoring.md, scripts/hash_password.sh
Add ingress for prometheus , alertmanager and thanos with basic auth.
1 . Added ingress for prometheus, alertmanager and thanos.
2 . Added basic auth with user and password pull from vault.
1 ) Deploy the changes in development  cluster  using command like :  make development terraform-apply  ENVIRONMENT=cluster4
2 ) Access enpoints using authentication.
Example
https://thanos.cluster4.development.teacherservices.cloud/
https://alertmanager.cluster4.development.teacherservices.cloud/
https://prometheus.cluster4.development.teacherservices.cloud/
=> Added Ingress and basic auth for prometheus,alertmanager and thanos

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Thanos compactor (test & prod) and prometheus (test) failing due to insufficient memory. 
Increase memory settings
make test terraform-plan (already applied manually)
=> Increase thanos compactor and prometheus memory

cluster/terraform_aks_cluster/config/development.tfvars.json
Number of nodes increased from 3 to 4 for dev cluster.
node_pools.app1 max_count set to 4
Login to azure console and go to AKS cluster , verify node pool apps1 max should be 4.
=>  Number of nodes increased for dev node_pool

cluster/terraform_kubernetes/config/prometheus/alertmanager/app_alert.rules.tmpl
##Trello card
https://trello.com/c/mwYIgitA/1713-alerts-bugs
This is a bugfix for the hardcoded values
remove hardcode and make affected alerts dynamic
hardcode has been removed
=> Fix bug in alert rules

cluster/terraform_kubernetes/config/production.tfvars.json
Alerts for Teacher Qualifications API, Teaching vacancies  and  Check the children’s barred list
Terraform plan :
`                   app:         get-school-experience-production
receiver: SLACK_WEBHOOK_GSE
+   - alert: High Memory Utilisation for check-childrens-barred-list-production
+     expr: sum by (namespace, container) (container_memory_working_set_bytes{container!="",image!="",namespace="tra-production",pod=~"check-childrens-barred-list-production-[a-z0-9]+-[a-z0-9]+"})/sum by (namespace, container) (kube_pod_container_resource_limits{container!="",namespace="tra-production",pod=~"check-childrens-barred-list-production-[a-z0-9]+-[a-z0-9]+",resource="memory"}) > 0.6
+     for: 5m
+     annotations:
+       summary:     check-childrens-barred-list-production high memory …
=> 1700 create alerts for all services  Teaching vacancies  and  Check the children’s barred list

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/rO6NTNwx/1700-create-alerts-for-all-services
Added monitoring for GIT App and GIT API
added GIT App and GIT API to the list of alertable apps in config
=> Added monitoring for GIT App and GIT API

cluster/terraform_kubernetes/grafana.tf
Update Grafana service type to ClusterIp , so that it will not exposed to public IP
Remove service type as LoadBalancer.
After deployment verify using below commands there is no External IP for grafana.
kubectl -n monitoring get svc   
NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
alertmanager           NodePort    10.0.254.155   <none>        9093:30383/TCP      7d2h
grafana                ClusterIP   10.0.221.216   <none>        3000/TCP            7d2h
kube-state-metrics     ClusterIP   None           <none>        8080/TCP,8081/TCP   7d2h
prometheus             ClusterIP   10.0.230.38    <none>        8080/TCP            7d2h
thanos-querier         ClusterIP   10.0.154.189   <none>        9090/TCP            7d2h
thanos-store-gateway …
=> Removed Service type as Loadbalancer

cluster/terraform_kubernetes/config/prometheus/development.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/platform-test.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/production.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/test.prometheus.yml, cluster/terraform_kubernetes/prometheus.tf
Prometheus doesn't reload its config automatically on yml or rules file changes
Add the reloader options to the thanos sidecar to monitor the config and trigger a reload if they are updated.
https://trello.com/c/4UgjfRDA/1714-add-thanos-reloader
Separate rules directory, config map and mount for alert rules
Add reloader options to the thanos sidecar command
- make development terraform-apply ENVIRONMENT=clusterx
- update terraform_kubernetes/config/development.tfvars.json with dummy alertable_apps and alertmanager_slack_receiver_list
- make development terraform-apply ENVIRONMENT=clusterx
- check prometheus & thanos logs and you should see a reload issued within a few minutes
- check changes are reflected in the prometheus ui
- make a change to …
=> Add thanos reloader for prometheus config changes

cluster/terraform_kubernetes/config/prometheus/alertmanager/app_alert.rules.tmpl
Tigger alert for pod restart or Crashloop
Updated query for alert 'High number of restarted containers'
Tested on cluster3 executing following command so that pod can restart.
1 ) go inside pod : kubectl -n development exec -it register-tope-75b79b7766-qn2xh -- sh 
2 ) Execute command : kill -1 -1.
3 ) check alertmanager https://prometheus.cluster3.development.teacherservices.cloud/alerts ,  alert [High number of restarted containers] will be firing.
=> Bug fix for trigger alerts for restart

templates/new_service/Makefile
When using the new service template, review app naming is {service-name}-{pr-number} instead of {service-name}-review-{pr-number}
https://trello.com/c/vDkMKGEI/1753-update-review-app-name-in-new-service-template
Update ENVIRONMENT value for review apps in template Makefile
check code
=> Update review app name in new service template

cluster/terraform_kubernetes/analytics.tf, documentation/aks-logs.md, documentation/logit-io.md
To lower log analytics costs.
Add two settings to ama-logs via config map.
Remove env vars from each ContainerInventory entry as it adds a lot of data that's not particularly useful 
- log_collection_settings.env_var = false
Allow exclude of log collection from pods with annotations fluentbit.io/exclude: "true".
- log_collection_settings.filter_using_annotations = true
Once applied, after a few minutes check ama-logs pods have restarted, then
kubectl -n kube-system logs pod/ama-logs-xxxx
and should see
config::configmap container-azm-ms-agentconfig for settings mounted, parsing values
config::Successfully parsed mounted config map
config::Using config map setting for cluster level environment variable collection
config::INFO: Using config map setting for annotation based log filtering …
=> Add log-data-collection-settings config map

cluster/terraform_aks_cluster/main.tf
https://trello.com/c/bLwwt7HH/1758-enable-workload-identity-on-all-clusters
Updated flags  oidc_issuer_enabled and workload_identity_enabled to enable OIDC
Terraform Plan for test :
~ update in-place
Terraform will perform the following actions:
~ resource "azurerm_kubernetes_cluster" "main" {
id                                  = "/subscriptions/20da9d12-7ee1-42bb-b969-3fe9112964a7/resourceGroups/s189t01-tsc-ts-rg/providers/Microsoft.ContainerService/managedClusters/s189t01-tsc-test-aks"
name                                = "s189t01-tsc-test-aks"
~ oidc_issuer_enabled                 = false -> true
+ oidc_issuer_url                     = (known after apply)
tags                                = {
"Environment"      = "Test"
"Product"          = "Teacher services cloud"
"Service …
=> OIDC enabled for all clusters

cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/variables.tf
Frequest false alarms such as https://ukgovernmentdfe.slack.com/archives/C05D5S8C6PJ/p1715079379398809
- Change the thresholds to 80%
- Remove the overrides when they are the same
- Fix json formatting
Run terraform plan
=> [1800] Reduce false alarms for cpu and memory

cluster/terraform_aks_cluster/analytics.tf, cluster/terraform_aks_cluster/config/production.tfvars.json, cluster/terraform_aks_cluster/main.tf, cluster/terraform_aks_cluster/variables.tf, documentation/developer-onboarding.md
From the Log Analytics review, add a data collection rule to select Container Insights logs we want and collection interval 
https://trello.com/c/JLoTqyxU/1795-add-data-collection-rule-for-cluster-monitor-data
- add data collection rule
- increase collection interval to 5m for non-prod clusters
- update omsagent auth, required for DCR 
- update dev documentation to reference ContainerLogV2 instead of ContainerLog
deploy a dev cluster and check logs are as expected 
Confirm there isn't any cluster outage on update 
- tested on cluster5 with apply review app and there was no service interruption during the update
=> Add data collection rule for ContainerInsight logs

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Thanos store gateway failing in test and prod clusters as 2G memory is insufficient
Increase to 3G
=> Increase thanos store gateway to 3G mem

cluster/terraform_aks_cluster/config/test.tfvars.json
Add more nodes to test cluster.
apps1 node pools max_count updated to 25
Terraform Plan  
`
~ resource "azurerm_kubernetes_cluster_node_pool" "node_pools" {
id                      = "/subscriptions/20da9d12-7ee1-42bb-b969-3fe9112964a7/resourceGroups/s189t01-tsc-ts-rg/providers/Microsoft.ContainerService/managedClusters/s189t01-tsc-test-aks/agentPools/apps1"
~ max_count               = 20 -> 25
name                    = "apps1"
tags                    = {}
}
Plan: 0 to add, 1 to change, 0 to destroy.
`
=> Test cluster max node count set to 25

README.md, documentation/azure-gcp-workload-identity-federation.md, scripts/azure-gcp-wif/create-gcp-workload-identity-pool-provider.sh, scripts/azure-gcp-wif/create-gcp-workload-identity-pool.sh
Add scripts and docs for workload identity federation. Trello card [here](https://trello.com/c/nbML53b1).
- Scripts for creating a workload identity pool and provider on GCP
- Basic documentation 
- Requires gcloud CLI and login for testing
=> Add docs and scripts for Azure -> GCP workload identity federation

.github/actions/deploy-environment/action.yml
azure/login action updated to use v2 to supress warning on node16 on pipelines.
Action  azure/login updated to use v2
There should be no warning related to node16 in pipeline.
=>  azure/login action updated to use v2

cluster/terraform_kubernetes/config/dashboards/nginx-ingress-controller.json
Filter by ingress is not working for ‘Controller Success Rate (non-4|5xx responses)’ on ingress dashboard.
Updated query by passing namespace and ingress
Deployed on test : https://grafana.test.teacherservices.cloud/d/nginx-test/nginx-ingress-controller-test.
Selected filter ingress namespace and ingress and check 'Controller Success Rate (non-4|5xx responses)'
=> Fixed filter Controller Success Rate by adding namespace and ingress

cluster/terraform_aks_cluster/config/production.tfvars.json
Production AKS Upgraded to 1.27.9.
Production AKS Upgraded to 1.27.9
Connect production cluster  : make production get-cluster-credentials CONFIRM_PRODUCTION=yes
Execute following command to check server version : kubectl version
=> Production AKS Upgraded to 1.27.9

cluster/terraform_kubernetes/ingress_controller.tf
The Apply for QTS service allows users to upload files up to 50 MB in size, so we need to ensure that the Nginx ingress proxy is be able to handle client body requests of that size.
=> Increase proxy body size to 50MB

documentation/maintenance-page.md, templates/new_service/Makefile
We need to update the maintenance template so it is easier to follow for implementation on services
- https://github.com/DFE-Digital/teacher-services-cloud/blob/main/templates/new_service/Makefile#L138 needs to be $(if ${MAINTENANCE_IMAGE_TAG},, $(eval export MAINTENANCE_IMAGE_TAG=$(shell date +%s)))
- Document the need for docker to be installed locally and running
- Step to create workflows for enable-maintenance and disable-maintenance
=> Update maintenance page template

scripts/konduit.sh
konduit will complete with a failure code if there is any failure in the cleanup step.
This causes workflows that use konduit to fail.
https://trello.com/c/rIg0hcYY/1892-konduit-ignore-cleanup-failures 
Update konduit to always complete the cleanup step with a success code
konduit.sh some-env -- psql
=> Ignore failures on cleanup step

templates/new_service/maintenance_page/scripts/failback.sh
There was a missing step in the maintenance page template
Add update image tag step into failback.sh for the maintenance page template
=> Add update image tag step for the maintenance page template

templates/new_service.sh
The naming of azure resources was not consistent
Fix naming in the template script
Run:
```
make new_service SERVICE_NAME=claim-additional-payments-for-teaching SERVICE_PRETTY="Claim additional payments for teaching" SERVICE_SHORT=capt DOCKER_REPOSITORY=ghcr.io/dfe-digital/claim-additional-payments-for-teaching NAMESPACE_PREFIX=srtl DNS_ZONE_NAME=claim-additional-teaching-payment.service.gov.uk
```
And check the generated domain files
=> [1750 Fix domain naming in template script

cluster/terraform_aks_cluster/config/development.tfvars.json, cluster/terraform_aks_cluster/config/platform-test.tfvars.json
AKS Upgrade to 1.28.9 on dev and platform-test cluster.
Dev Cluster and Platform test cluster upgraded.
Verify platform test cluster already upgraded  check using 'kubectl get  node' .
=> AKS Upgrade 1.28.9 on dev and platform-test

documentation/logit-io.md
All rails 404 route error requests return a large stack trace to the logs, which we send to the logs.
Will be slow to get all the services to fix, so might be easier to drop in logit.
https://kibana-uk1.logit.io/s/e9b9162d-0b5e-4362-bed0-8e577f88d06e/app/discover#/doc/filebeat-*/filebeat-2024.07.08?id=GNWDkZABnFDrG26tbgNT
Add a filter to drop app.exception.stack_trace if [app.exception.name] is "ActionController::RoutingError" 
No more stack traces in logit for these messages
=> Drop route error stack traces

documentation/logit-io.md
Remove the query strings in the ingress logs as they may contain personal data. Sensitive fields are obfuscated in app logs, but not in ingress logs.
Add the filter to the logstash pipeline documentation
Observe the `<QUERY STRING STRIPPED>` in ingress logs
=> [1909] Update logstash pipeline

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
WIF is live in the BAT apps. We can start migrating TRA apps now, especially TRS as it's the first dotnet app.
Add Google WIF to all TRA namespaces
=> Add workload identity federation to TRA namespaces

scripts/konduit.sh
Simplify use of konduit when using a non default database or database server. Useful in case of an incident.
- Override database name
- Override database server
- Simplify some parts of the code
- Connect to apply-qa postgres: `scripts/konduit.sh  apply-qa -- psql`
- Create new database: `create database abcd123;`
- Connect to new postgres: `scripts/konduit.sh -d abcd123 apply-qa -- psql`
- Delete temp database: `drop database abcd123;` ⚠️ 
- Connect to apply-qa redis default DB: `scripts/konduit.sh  apply-qa -- redis-cli`
- Connect to apply-qa redis DB database 1: `scripts/konduit.sh -d 1 apply-qa -- redis-cli`
- Connect to register-qa postgres using debug: `bash -x scripts/konduit.sh  register-qa -- psql`
- Write down the value of ORIG_URL
- Connect to register qa postgres using apply …
=> [1863] Update konduit to pass database URL

cluster/terraform_kubernetes/config/dashboards/k8s-views-pod.json
In Grafana OOM Events by pod not showing any OOM Killed.
Have used the metric kube_pod_container_status_restarts_total to capture OOM Killed. 
1.  Simulate pod restart by OOM Killed  by following steps
`   kubectl -n bat-qa exec -it apply-qa-bb9c96bc4-lmw6z -- sh
apk add --no-cache stress-ng
stress-ng  -vm 1 --vm-bytes 1024M --timeout 10s
`
2. Check Grafana dashboard 'k8s_views_pods' , the OOM Events by pod should the events.
NA
NA
=> Fixed issue by updating the query for OOM events by pod widget

cluster/terraform_kubernetes/config/dashboards/k8s-views-global.json, cluster/terraform_kubernetes/config/dashboards/k8s-views-namespaces.json
OOMKilled dashboard query fix
Update dashboards global and namespace , used metric kube_pod_container_status_restarts_total
Verrify OOM Killed events in Gloabla and namespace dashbaords
NA
NA
=> OOMKilled query fixed on global and namespace dashboards

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/variables.tf
Block  metric endpoints for all production services.
Added annotation to block metrics endpoint.
After deploying ,  metric  endpoint should not be  accessible  to  any service.
Testing done on dev cluster2 https://apply-review-2222.cluster2.development.teacherservices.cloud/metrics
Terraform plan :
+ set {
+ name  = "controller.config.server-snippet"
+ type  = "string"
+ value = <<-EOT
location /metrics {
deny all;
}
EOT
}
=> Added annotation to block metric enpoint

cluster/terraform_aks_cluster/config/development.tfvars.json
We are running into issues during the deployments post AKS cluster deployment due to enough nodes not being in a ready state.
Increase the minimum number of nodes for apps1 nodepool within the development.tfvars for the AKS cluster deployment to 3.
Ensure deployment of K8s cluster for development cluster doesn’t have the same issues logged in https://trello.com/c/le9lI9EQ/1981-increase-minimum-nodes-for-app1-nodepool-aks-terraform-development and has a clean run the first time.
=> Increase minimum node for app1 nodepool

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
https://trello.com/c/rPsNKgib/1989-monitoring-increase-thanos-memory
Some thanos pods are failing with OOM
Increase memory from 4Gi to 5Gi for thanos-store-gateway in test
Increase memory from 6Gi to 7Gi for thanos-compactor in prod
make env terraform-plan
kubectl -n monitoring get pods (to see restarts)
=> Thanos memory increases

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/thanos.tf
thanos-store-gateway not running
- it was failing the liveness probe so increased probe settings
- once probe increased it was failing with OOM
Increase liveness probe interval and memory
=> Update memory and liveness probe for thanos-store

templates/new_service/.gitignore
terraform/domains/infrastructure/vendor is missing and may cause issues in new services
Add terraform/domains/infrastructure/vendor to .gitignore
Compare with deployed services
=> [1994] Update new_service template .gitignore

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
We use [version 4.8.3](https://github.com/DFE-Digital/teacher-services-cloud/blob/18482f44ee47d1738e2cb151610d2da5c266071d/cluster/terraform_kubernetes/config/production.tfvars.json#L34). The latest version is [4.11.](https://github.com/kubernetes/ingress-nginx/releases)0. We should not fall behind as it is a critical component and it may be tied to the kubernetes version.
Upgrade ingress controller version to 4.11.0
=> Upgrade the ingress controller version for dev, plaftform-test and test environments

cluster/terraform_aks_cluster/.terraform.lock.hcl, cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/grafana.tf, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/thanos.tf, cluster/terraform_kubernetes/welcome_app.tf
Added security context  fixes to welcome app , ingress , prometheus ,thanos and grafana
Added security_context  to container with following attributes.
`
security_context {
run_as_user  = 1000
run_as_group = 3000
capabilities {
add  = ["NET_BIND_SERVICE"]
drop = ["ALL"]
}
allow_privilege_escalation = false
privileged                 = false
run_as_non_root            = true
read_only_root_filesystem  = true
seccomp_profile {
type = "RuntimeDefault"
}
}
`
Deployed on cluster2 , this can be tested.
https://www.cluster2.development.teacherservices.cloud/
https://prometheus.cluster2.development.teacherservices.cloud/
https://thanos.cluster2.development.teacherservices.cloud/
https://grafana.cluster2.development.teacherservices.cloud/ …
=> Added security context fixes

cluster/terraform_kubernetes/config/production.tfvars.json
We use [version 4.8.3](https://github.com/DFE-Digital/teacher-services-cloud/blob/18482f44ee47d1738e2cb151610d2da5c266071d/cluster/terraform_kubernetes/config/production.tfvars.json#L34). The latest version is [4.11.](https://github.com/kubernetes/ingress-nginx/releases)0. We should not fall behind as it is a critical component and it may be tied to the kubernetes version.
Update ingress controller version to 4.11.0 for production
=> Upgrade the ingress controller version for prod

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Revert ingress  ngnix version to 4.8.3
Revert ingress  ngnix version to 4.8.3
https://grafana.test.teacherservices.cloud/d/nginx/nginx-ingress-controller?orgId=1&refresh=10m
https://grafana.platform-test.teacherservices.cloud/d/nginx/nginx-ingress-controller?orgId=1&refresh=10m
=> Revert ingress  ngnix version to 4.8.3

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/ingress_controller.tf
The upgrade was reverted as the dashboard was empty. We still want to upgrade, with a working dashboard.
Expose ingress controller prometheus metrics. It must be required explicitly in the 4.11.0 version.
- Working dashboard: https://grafana.cluster1.development.teacherservices.cloud/d/nginx/nginx-ingress-controller?orgId=1&refresh=10m&editIndex=1&from=now-5m&to=now
- Example of nginx metrics: https://prometheus.cluster1.development.teacherservices.cloud/graph?g0.expr=nginx_ingress_controller_requests&g0.tab=1&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=1h
=> [1919] Upgrade ingress controller to 4.11.0 with metrics enabled

cluster/terraform_aks_cluster/config/production.tfvars.json
Upgrading production for AKS nodes to 1.29.7
Upgrading production for AKS nodes to 1.29.7
Check pods are all healthy in production cluster and running. Validate domains are still valid.
=> updating aks version for production to 1.29.7

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/variables.tf
Upgrade monitoring  components to latest version
Upgraded to following versions.
prometheus v2.54.1 
alertmanager v0.27.0 
thanos v0.36.1 
grafana 11.1.5 
node exporter v1.8.2 
kube state metrics: 2.12.0 ( AKS 1.29)
Deployed on cluster2 all metrics are coming.
Grafna features : https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v11-0/
=> Version Upgrade for monitoring components

cluster/terraform_kubernetes/prometheus.tf, cluster/terraform_kubernetes/thanos.tf
Monitoring data is not being transferred to azure by thanos
From the thanos container
```
ts=2024-09-23T13:23:53.020231501Z caller=sidecar.go:410 level=warn err="upload 01xxxxxxx: hard link block: hard link file chunks/000001: link /prometheus/01xxxxxxxx/chunks/000001 /prometheus/thanos/upload/01xxxxxxx/chunks/000001: operation not permitted" uploaded=0
$ ls -l /prometheus/
total 48
drwxr-xr-x    3 1000     3000          4096 Sep 24 03:00 01xxxxx
drwxr-xr-x    3 1000     3000          4096 Sep 24 05:00 01xxxxx1
drwxr-xr-x    3 1000     3000          4096 Sep 24 07:00 01xxxxx2
drwxr-xr-x    2 1000     3000          4096 Sep 24 08:01 chunks_head
-rw-r--r--    1 1000     3000         20001 Sep 24 08:11 queries.active
drwxr-x---    3 thanos   thanos        4096 Sep 12 16:06 thanos
-rw-r--r-- …
```
=> Set container uid,gid for thanos monitoring

documentation/Ingress-controller-upgrade.md, documentation/aks-upgrade.md
Upgrades to AKS or ingress-controller may break the metrics and Grafana dashboards.
Add a step to check dashboards in:
[teacher-services-cloud/documentation/aks-upgrade.md at main · DFE-Digital/teacher-services-cloud](https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/aks-upgrade.md)
[teacher-services-cloud/documentation/Ingress-controller-upgrade.md at main · DFE-Digital/teacher-services-cloud](https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/Ingress-controller-upgrade.md)
Review the additional step in the documentation
=> Add grafana dashboard check step after upgrades

.github/workflows/deploy-cluster.yml
When the workflow fails at any point we don’t get a notification and we don’t know it happened.
We should send a notification to #teacher-service-infra Slack channel with a link to the failed workflow.
Add slack notifications with links for pipeline failures
=> Notify when cluster update fails

.gitignore, Makefile, templates/new_service/Makefile
Usage of terrafile only supports x86_64 architecture and does not provide support for apple silicon arm based processors. This PR adds support for different processor architectures.
- Update the terrafile commands in makefile to support different process architectures.
- Update the .gitignore to ignore jetbrains .idea directory 
- Users on mac should now be able to use makefile and execute commands.
- Users on windows will be able to use makefile as before.
N/A
N/A
=> Enable different processor arch

documentation/developer-onboarding.md
developers have clear link to the infrastructure team sharepoint docs
add link to infrastructure team sharepoint docs
check link works and see extra info on searching documentation
=> add link to infrastructure team sharepoint docs

documentation/maintenance-page.md, templates/new_service/maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
fix bug and improve documentation in maintenance page 
- fix bug in maintenance github workflow template related to docker repository parameter.
- add documentation on setting permissions for package image built
make new_service SERVICE_NAME=apply-for-qts SERVICE_SHORT=afqts SERVICE_PRETTY="Apply for qualified teacher status" DOCKER_REPOSITORY=ghcr.io/dfe-digital/apply-for-qualified-teacher-status NAMESPACE_PREFIX=tra DNS_ZONE_NAME=apply-for-qts-in-england.education.gov.uk
check new_service/.github/workflows/maintenance.yml has correct docker repository value
review documentation change for correctness
=> Maintenance Page template correction and documentation addition

custom_domains/terraform/infrastructure/config/tscp_Terrafile
The txt_record_list feature is now released to stable
Change prod custom domain terrafile to stable
Run `make prod-domain domains-infra-plan CONFIRM_PROD_DOMAIN=yes`
It should work and show no change
=> [2137] Use stable terraform module in production custom_domains

templates/new_service/terraform/domains/environment_domains/main.tf
The standard is to use the default value
Remove null_host_header
https://github.com/DFE-Digital/register-early-career-teachers/pull/756
=> [2105] Remove null_host_header option from domains template

documentation/logit-io.md
The field was interpreted as either string or number (ecf is uuid, npq is integer)
Enforce type string using Logstash
This was applied manually for a week already
Check the field is not in conflict in kibana
=> [2138] Process current_user_id in logstash

cluster/terraform_aks_cluster/config/platform-test.tfvars.json
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality. Our clusters are currently on 1.29
Upgrade the Kubernetes cluster from 1.29.7 to 1.30.6.
platform-test cluster configuration for kubernetes cluster, orchestrator version for all node pools from 1.29.7 to 1.30.6
=> platform-test: Upgrade AKS from 1.29.7 to 1.30.6

cluster/terraform_aks_cluster/config/test.tfvars.json
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality. Our clusters are currently on 1.29
Upgrade the Kubernetes cluster from 1.29.7 to 1.30.6.
Test cluster configuration for kubernetes cluster, orchestrator version for all node pools from 1.29.7 to 1.30.6
=> test: Upgrade AKS from 1.29.7 to 1.30.6

documentation/disaster-recovery-testing.md, documentation/disaster-recovery.md
Improve disaster recovery docs based on latest claims dr test
improve docs about removing azure Monitor Diagnostic settings
add examples of urls after maintenance page enabled. 
review correctness of changes and format and spelling.
=> Improve disaster recovery docs

cluster/terraform_aks_cluster/config/production.tfvars.json, documentation/aks-upgrade.md
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality. Our clusters are currently on 1.29
Upgrade the Kubernetes cluster from 1.29.7 to 1.30.6.
production cluster configuration for Kubernetes cluster, orchestrator version for all node pools from 1.29.7 to 1.30.6
https://trello.com/c/UAxI1HVZ
=> prod: Upgrade AKS from 1.29.7 to 1.30.6

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
srtl namespaces need to be enabled for gcp wif so application in these namespaces can be configured for gcp wif
add the srtl namespaces to config for aks test cluster and production cluster
review change for any typos.
=> Enable srtl namespaces  for gcp wif

Makefile, cluster/terraform_aks_cluster/.terraform.lock.hcl, cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/data.tf, cluster/terraform_kubernetes/github_actions_wif.tf, cluster/terraform_kubernetes/output.tf, cluster/terraform_kubernetes/variables.tf, documentation/onboard-service.md, templates/new_service/.github/workflows/backup-db.yml, templates/new_service/.github/workflows/build-and-deploy.yml, templates/new_service/.github/workflows/delete-review-app.yml, templates/new_service/.github/workflows/maintenance.yml, templates/new_service/.github/workflows/postgres-ptr.yml, templates/new_service/.github/workflows/postgres-restore.yml, templates/new_service/Makefile, templates/new_service/terraform/application/terraform.tf
Create federated credentials so that github actions for all services can authenticate using OIDC instead of service principal secret
Depends on:
- https://github.com/DFE-Digital/github-actions/pull/106
- https://github.com/DFE-Digital/terraform-modules/pull/140
- Create managed identities and federated credentials for ITTMS and Publish
- Update new_service template
- Update documentation
- See https://github.com/DFE-Digital/itt-mentor-services/pull/1253
- Review documentation
=> [2151] Enable Github actions OIDC for services

Makefile, cluster/terraform_aks_cluster/azure_metric_alerts.tf, cluster/terraform_aks_cluster/variables.tf, documentation/monitoring.md
We need a way to alert when our nodepool is close to max capacity to preempty scaling if necessary.
Adding an Azure Monitor Metric Alert with an Action group for each environment and dynamically setting the threshold based on the max count.
This has been checked in the Azure Monitor UI and is correctly working.
=> Adding Azure monitor metrics to TSC repo for node availability

cluster/terraform_aks_cluster/azure_metric_alerts.tf, documentation/monitoring.md
We want to be alerted if SNAT port exhaustion happens on the kubernetes load balancer as well as when port usage is high on the load balancer for a node. 
Two Azure alerts created with actions to send to slack. 
I don't believe we can use prometheus for this as the load balancer is outside of kubernetes so does report info to prometheus AFAIK. 
this has been applied to the platform test environment via 
make platform-test terraform-aks-cluster-apply CONFIRM_PLATFORM_TEST=yes
so can be seen in the azure portal. 
Not user which slack webhook to use. 
To test the slack integration we could set the ConnectionState to Success instead of Failed to generate an alert 
and reduce the port threshold from 900 to a small value to test the only alert.
=> SNAT port exhaustion alerting

documentation/logit-io.md
Improve docs on logit elastalert
add reference to new email address alert 
add link to docs for writing alerts 
review for spelling format and link working 
https://trello.com/c/Y6Qmb2Jk/2192-logit-alert-for-sensitive-data-emails
- [x ] I have performed a self-review of my code, including formatting and typos
- [x ] I have [cleaned the commit history](https://www.annashipman.co.uk/jfdi/good-pull-requests.html)
=> Improve docs on logit elastalert

cluster/terraform_kubernetes/alertmanager.tf, cluster/terraform_kubernetes/reloader.tf, cluster/terraform_kubernetes/variables.tf
Adding reloader to the cluster with Terraform resources
Adding reloader to the cluster with Terraform resources
Change a config map when the annotation for reloader is applied and watch the deployment dynamically restart
=> Alertmanager config reloader container

cluster/terraform_kubernetes/reloader.tf
Correcting namespace for reloader and adding RBAC permissions
Changing namespace to monitoring and adding RBAC for cronjobs API
Check logs for pod and namespace
=> feat: Correcting RBAC errors

cluster/terraform_kubernetes/github_actions_wif.tf
ga_wif naming doesn't include the dev cluster env, so cluster build fails if one already exists
Error: A resource with the ID "/subscriptions/nnnnnnn/resourceGroups/s189d01-tsc-dv-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/s189d01-ga-wif-development-bat-id" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_user_assigned_identity" for more information.
use var.environment instead of var.config
this will create s189d01-ga-wif-**clustern**-bat-id  instead of s189d01-ga-wif-**development**-bat-id
see dev cluster 1
make env deploy-plan makes no changes to test, production clusters
=> Add dev cluster env to ga_wif naming

.github/actions/test-app-deployment/action.yml
The 843-github-actions-oidc ITTM branch was merged to main so we don't need to pin this branch anymore
Remove branch pinning
Successful run: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/12890121135/job/35946771086
=> [2151] Update ITTMS branch

templates/new_service/.github/workflows/build-and-deploy.yml, templates/new_service/terraform/domains/environment_domains/output.tf
adding workflows for domain deployment to build workflows 
this is the updated template for  build_and_deploy.yml adding calls to the deploy domains github actions. 
review the actions to see the workflows being running. 
review code and decide on best architecture
can see test runs for jobs added to  build_and_deploy.yml  run as separate test runs but doing plan not apply
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/12829975027
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/12829975022 (this only fails because plan doesn't see output variable like apply so will success for appply)
[Implement CI/CD for domains on all services](https://trello.com/c/unElJf6I/2168-implement-ci-cd-for-domains-on-all-services)
=> CI-CD for domains

.github/actions/test-app-deployment/action.yml
The main tag is not deterministic and might deploy an old image if it's cached on the AKS node
Determine the latest commit id and use it to determine the latest docker tag
Successful run: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/12928764567/job/36056753462
=> [2151] Deploy ITTMS latest commit tag instead of "main"

documentation/production-checklist.md
Capture more good practices in the doc
Add:
- caching
- redirects
- docker pinning
- documenting secrets
Review documentation
=> [856] Update production checklist

documentation/logit-io.md
Added logit logstash pipeline update that suppresses "DfE::Analytics::SendEvents" messages from our logit stacks.
The changes were made as these messages are considered unnecessary at present, and we send too many.
Documentation update
The change can be seen in the test and prod logit logstash pipelines
=> Add logit DfEAnalyticsSendEvents msg supression

documentation/platform-faq.md
Adding documentation for OIDC error and solution with greater detail
Doc update
=> fix: Adding to documentation for FAQ

cluster/terraform_kubernetes/config/test.tfvars.json
prometheus on the test cluster is failing with OOM
Increase memory from 12G to 14G
=> Increase prometheus memory from 12G to 14G

documentation/platform-faq.md, scripts/konduit.sh
The script was not stopping when an error happened, which made it more difficult to troubleshoot errors
Make the script more robust by configuring "set -eu" to stop when there is an error and when a variable is not set
Try konduit with various commands and arguments:
- scripts/konduit.sh apply-staging -- psql
- scripts/konduit.sh apply-staging -- redis-cli
- scripts/konduit.sh -a apply-review-10343  -- redis-cli
- scripts/konduit.sh apply-review-10343 --  pg_dump -E utf8 --clean --compress=1 --if-exists --no-owner --verbose --no-password -f bak.gz
- scripts/konduit.sh -c -i bak.gz apply-review-10343 -- psql
- scripts/konduit.sh -t 120 -n bat-qa apply-review-10343 -- psql
- scripts/konduit.sh -k s189t01-gse-stg-inf-kv -d gse-staging get-school-experience-staging  -- psql
- …
=> [2242] Improve konduit.sh error handling

scripts/konduit.sh
The simple set -eu doesn't prevent failure when commands are piped to each other
Add -o pipefail to detect failure even when using a pipe
See explicit failure in https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/13265051999/job/37032437831
Try konduit with various commands and arguments:
- scripts/konduit.sh apply-staging -- psql
- scripts/konduit.sh apply-staging -- redis-cli
- scripts/konduit.sh -a apply-review-10343  -- redis-cli
- scripts/konduit.sh apply-review-10343 --  pg_dump -E utf8 --clean --compress=1 --if-exists --no-owner --verbose --no-password -f bak.gz
- scripts/konduit.sh -c -i bak.gz apply-review-10343 -- psql
- scripts/konduit.sh -t 120 -n bat-qa apply-review-10343 -- psql
- scripts/konduit.sh -k s189t01-gse-stg-inf-kv -d gse-staging …
=> [2242] Add -o pipefail to konduit.sh

documentation/platform-faq.md
Adding to Doc as resource group being missing from the group role assignments can be an additional source of failure.
=> fix: Adding to faq doc for OIDC

cluster/terraform_aks_cluster/config/platform-test.tfvars.json
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality.
Upgrade the Platform Test Kubernetes cluster from 1.30.6 to 1.31.5.
Test cluster configuration for kubernetes cluster, orchestrator version for all node pools from 1.30.6 to 1.31.5
https://trello.com/c/Gb9zGC6R/2255-aks-upgrade-to-131
=> Upgrading the AKS platform-test cluster from 1.30.6 to 1.31.5

cluster/terraform_aks_cluster/config/test.tfvars.json
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality.
Upgrade the Test Kubernetes cluster from 1.30.6 to 1.31.5.
Test cluster configuration for kubernetes cluster, orchestrator version for all node pools from 1.30.6 to 1.31.5
https://trello.com/c/Gb9zGC6R/2255-aks-upgrade-to-131
=> Upgrading the AKS test cluster from 1.30.6 to 1.31.5

cluster/terraform_aks_cluster/config/production.tfvars.json
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality.
Upgrade the Prod Kubernetes cluster from 1.30.6 to 1.31.5.
Test cluster configuration for kubernetes cluster, orchestrator version for all node pools from 1.30.6 to 1.31.5
https://trello.com/c/Gb9zGC6R/2255-aks-upgrade-to-131
=> Upgrading the AKS prod cluster from 1.30.6 to 1.31.5

cluster/terraform_kubernetes/config/production.tfvars.json
A critical vulnerability CVE-2025-1974 in ingress-nginx needs to be fixed. 
https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974
Update the ingress-nginx helm chart to version 4.11.5 on development environments
Nginx-ingress 4.11.5 is running successfully on dev, platform-test and test environments.
PR for test environment - https://github.com/DFE-Digital/teacher-services-cloud/pull/405
=> Update nginx controller to 4.11.5

.github/workflows/cluster_access_test.yml
=> fix: 2309-cluster-access-smoke-test: missing cluster name in slack alert

cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/grafana.tf, cluster/terraform_kubernetes/terraform.tf, documentation/grafana.md
We need to implement secure authentication for our Grafana monitoring dashboard. Using Microsoft Entra ID (Azure AD) authentication allows us to leverage our existing identity provider for role-based access control, centralizing user management and enhancing security by eliminating anonymous access.
- Created an Azure AD application registration for Grafana SSO with appropriate redirect URIs
- Configured three application roles (Admin, Editor, Viewer) for granular access control
- Updated Grafana deployment with comprehensive Azure AD authentication environment variables
- Disabled anonymous access to enforce authenticated sessions only
- Fixed ingress configuration to ensure proper frontend asset loading
- Implemented modern OAuth security practices including PKCE and proper scoping
- …
=> Enable Single Sign-On for Grafana via AzureAD

cluster/terraform_kubernetes/.terraform.lock.hcl, cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the alertmanager receiver config for capt
Adding the alertmanager receiver config for capt
receiver available in alertmanager UI
k port-forward alertmanager-7bcb4b54c6-429kf -n monitoring 9093:9093
```
- receiver: SLACK_WEBHOOK_CAPT
match:
receiver: SLACK_WEBHOOK_CAPT
continue: false
group_interval: 1m
repeat_interval: 1h
```
=> Adding the alertmanager receiver config for capt

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the alertmanager receiver config for rotp
Adding the alertmanager receiver config for rotp
receiver available in alertmanager UI
```
- receiver: SLACK_WEBHOOK_ROTP
match:
receiver: SLACK_WEBHOOK_ROTP
continue: false
group_interval: 1m
repeat_interval: 1h
```
=>  Adding the alertmanager receiver config for rotp

cluster/terraform_aks_cluster/config/test.tfvars.json
Test cluster apps1 nodepool is getting close to its current max size (25 nodes)
Increase max size to 30 nodes
=> Increase test cluster apps1 nodepool max to 30

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the alertmanager receiver config for aytq
Adding the alertmanager receiver config for aytq
receiver available in alertmanager UI
```
- receiver: SLACK_WEBHOOK_AYTQ
match:
receiver: SLACK_WEBHOOK_AYTQ
continue: false
group_interval: 1m
repeat_interval: 1h
```
=> Adding the alertmanager receiver config for aytq

cluster/terraform_kubernetes/config/production.tfvars.json
Alerts configured for ecf prod and sandbox env for High Memory and CPU
Alerts configured for ecf prod and sandbox env for High Memory and CPU
Alerts available in Prometheus UI
k port-forward prometheus-557dd498c8-x2rw2 9090:9090 -n monitoring
http://localhost:9090/alerts?search=
look for cpd-ecf alerts
=> Alerts configured for ecf prod and sandbox env for High Memory and CPU

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Adding the alertmanager receiver config for CTP
Adding the alertmanager receiver config for CTP
receiver available in alertmanager UI
k port-forward alertmanager-7bcb4b54c6-429kf -n monitoring 9093:9093
```
- receiver: SLACK_WEBHOOK_CTP
match:
receiver: SLACK_WEBHOOK_CTP
continue: false
group_interval: 1m
repeat_interval: 1h
```
=> feat(2354): added deployment monitoring webhook for CTP

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Alerts need to be configured for ec2 staging, prod and sandbox env for High Memory and CPU
Add configuration to create alerts
Alerts should be visible in prometheus ui
=> Alerts configured for ec2

cluster/terraform_kubernetes/config/test.tfvars.json
test cluster prometheus failing with OOM
Increase memory from 17G to 18G
make test terraform-kubernetes-plan (already applied)
=> Increase test prometheus memory to 18G

cluster/terraform_kubernetes/config/test.tfvars.json
prometheus in the test cluster requires more memory
Increase from 18G to 19G
make test terraform-kubernetes-plan (already applied)
=> Increase test prometheus memory to 19G

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Correcting deployment name for CPD EC2
Ensure pipelines run successfuly
=> Correct CPD deployment names for alerting

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
Need to correct deployment names so that they can be picked by by the alertmanager app rule templates correctly.
Adding the full deployment names for this which are ambiguous
Check app templates render with correct values using -
`make production terraform-kubernetes-plan CONFIRM_PRODUCTION=yes` locally
Validate pipeline runs
=> Correct deployment names

cluster/terraform_kubernetes/config/test.tfvars.json
prometheus deployment in test requires more memory
Increase from 19G to 21G
make test terraform-kubernetes-plan (already deployed manually)
=> Increase prometheus memory to 21G

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
receiving high cpu alerts in #infra-public-alert slack channel for thanos-compactor
- increase alertmanager max_cpu threshold from 0.8 to 0.99 for thanos_compactor
=> chore(prom thanos-compactor amended alerting): cpu alertmanager threshold increase

cluster/terraform_kubernetes/config/prometheus/development.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/platform-test.prometheus.yml, cluster/terraform_kubernetes/config/prometheus/test.prometheus.yml
- Add dedicated nginx-ingress scrape job with metric relabeling
- Drop high-cardinality labels from nginx_ingress_controller_.*_bucket metrics
- Remove instance, kubernetes_pod_name, pod_template_hash, controller_pod, nodename labels
- Preserve essential monitoring labels (ingress, service, method, status, le)
- Exclude nginx pods from general kubernetes-pods job to prevent double-scraping
- Add documentation capturing changes and affected metrics
Reduces cardinality from 1.5m+ to manageable levels while
maintaining service-level monitoring capabilities.
You can compare the total series between cluster2 and cluster6 to see the reduced series across all nginx bucket histogram metrics
https://prometheus.cluster2.development.teacherservices.cloud/graph?g0.expr=count(nginx_ingress_controller_r …
=> feat(prometheus): reduce nginx ingress cardinality

cluster/terraform_kubernetes/config/prometheus/production.prometheus.yml
Applying label drops to production
Same as for test and platform-test extended to k8s.
Validate metrics have dropped and Prometheus is using less memory
=> Label drop production cluster metrics

cluster/terraform_kubernetes/config/production.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json, cluster/terraform_kubernetes/ingress_controller.tf, cluster/terraform_kubernetes/variables.tf
Update memory limits for prometheus and nginx
Decrease prometheus memory limit in test and prod clusters as tuning has lowered the memory usage
Increase nginx memory limit as usage has increased in the test cluster and we are seeing more frequent memory alerts
make test|production terraform-kubernetes-plan
update to 600Mi for nginx tested manually against platform-test
=> 2461 aks deployment memory

cluster/terraform_kubernetes/config/development.tfvars.json, cluster/terraform_kubernetes/config/platform-test.tfvars.json
- maintain versions nearer to current
https://trello.com/c/0DmNvcxN/2488-upgrade-ingress-nginx
- bump controller version from 4.11.5. to 4.12.6
development:
test:
checked garafana dashboards still available for dev and platform-test
https://grafana.cluster3.development.teacherservices.cloud/dashboards
https://grafana.platform-test.teacherservices.cloud/dashboards
N/A
N/A
=> feat(2488): bump controller version in dev and platform-test

cluster/terraform_aks_cluster/config/test.tfvars.json, cluster/terraform_kubernetes/config/test.tfvars.json
- keep kubernetes versions up to date
-  https://trello.com/c/suqcFfwt/2445-aks-upgrade-from-1315-to-1326
- upgrade test AKS cluster from 1.31.5 to 1.32.6
tested an itt review app:-
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/17559797012/job/49873274962
N/A
- i need to prep the PR for the manually applied nginx upgrade
=> feat(2445): AKS upgrade & ingress-controller upgrade in test environment
